//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPNS.TransitiveMiddleware.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APP_bUseFileLog {
            get {
                return ((bool)(this["APP_bUseFileLog"]));
            }
            set {
                this["APP_bUseFileLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NET_ListeningSocketCount {
            get {
                return ((int)(this["NET_ListeningSocketCount"]));
            }
            set {
                this["NET_ListeningSocketCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int NET_MWTimeout {
            get {
                return ((int)(this["NET_MWTimeout"]));
            }
            set {
                this["NET_MWTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logs")]
        public string LOG_LogFilePath {
            get {
                return ((string)(this["LOG_LogFilePath"]));
            }
            set {
                this["LOG_LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYS")]
        public string LOG_SystemLogFilename {
            get {
                return ((string)(this["LOG_SystemLogFilename"]));
            }
            set {
                this["LOG_SystemLogFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APP")]
        public string LOG_ApplicationLogFilename {
            get {
                return ((string)(this["LOG_ApplicationLogFilename"]));
            }
            set {
                this["LOG_ApplicationLogFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_bDateAppendToLogFileName {
            get {
                return ((bool)(this["LOG_bDateAppendToLogFileName"]));
            }
            set {
                this["LOG_bDateAppendToLogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public int NET_BufferSize {
            get {
                return ((int)(this["NET_BufferSize"]));
            }
            set {
                this["NET_BufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int NET_MaxPacketSize {
            get {
                return ((int)(this["NET_MaxPacketSize"]));
            }
            set {
                this["NET_MaxPacketSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RFID_MinTagReadCount {
            get {
                return ((int)(this["RFID_MinTagReadCount"]));
            }
            set {
                this["RFID_MinTagReadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RFID_GateInOutMergeTime {
            get {
                return ((int)(this["RFID_GateInOutMergeTime"]));
            }
            set {
                this["RFID_GateInOutMergeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int APP_MAXListCount {
            get {
                return ((int)(this["APP_MAXListCount"]));
            }
            set {
                this["APP_MAXListCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string RFID_Check_Last_State {
            get {
                return ((string)(this["RFID_Check_Last_State"]));
            }
            set {
                this["RFID_Check_Last_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int APP_DisconnectDislayTime {
            get {
                return ((int)(this["APP_DisconnectDislayTime"]));
            }
            set {
                this["APP_DisconnectDislayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int RFID_Last_State_Interval {
            get {
                return ((int)(this["RFID_Last_State_Interval"]));
            }
            set {
                this["RFID_Last_State_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bpns")]
        public string APP_Exit_Password {
            get {
                return ((string)(this["APP_Exit_Password"]));
            }
            set {
                this["APP_Exit_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APP_bPreventDoubleRun {
            get {
                return ((bool)(this["APP_bPreventDoubleRun"]));
            }
            set {
                this["APP_bPreventDoubleRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RFID_Threshold_Count {
            get {
                return ((int)(this["RFID_Threshold_Count"]));
            }
            set {
                this["RFID_Threshold_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RFID_bCheckCarNoFormat {
            get {
                return ((bool)(this["RFID_bCheckCarNoFormat"]));
            }
            set {
                this["RFID_bCheckCarNoFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPNSOLUTION")]
        public string DB_SID {
            get {
                return ((string)(this["DB_SID"]));
            }
            set {
                this["DB_SID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112.162.225.130")]
        public string DB_HostName {
            get {
                return ((string)(this["DB_HostName"]));
            }
            set {
                this["DB_HostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORACLE")]
        public string DB_Type {
            get {
                return ((string)(this["DB_Type"]));
            }
            set {
                this["DB_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HIDB1")]
        public string DB_Name {
            get {
                return ((string)(this["DB_Name"]));
            }
            set {
                this["DB_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prodc86e")]
        public string DB_Pass {
            get {
                return ((string)(this["DB_Pass"]));
            }
            set {
                this["DB_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C86E")]
        public string DB_UserID {
            get {
                return ((string)(this["DB_UserID"]));
            }
            set {
                this["DB_UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int NET_EQErrorCheckTime {
            get {
                return ((int)(this["NET_EQErrorCheckTime"]));
            }
            set {
                this["NET_EQErrorCheckTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8091")]
        public int FROM_PAMS_PORT {
            get {
                return ((int)(this["FROM_PAMS_PORT"]));
            }
            set {
                this["FROM_PAMS_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int DB_Timeout {
            get {
                return ((int)(this["DB_Timeout"]));
            }
            set {
                this["DB_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DB_Batch_Timeout {
            get {
                return ((int)(this["DB_Batch_Timeout"]));
            }
            set {
                this["DB_Batch_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public int SMSResendSecond {
            get {
                return ((int)(this["SMSResendSecond"]));
            }
            set {
                this["SMSResendSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int POWER_SMSSendTerm {
            get {
                return ((int)(this["POWER_SMSSendTerm"]));
            }
            set {
                this["POWER_SMSSendTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int POWER_ShutdownTerm {
            get {
                return ((int)(this["POWER_ShutdownTerm"]));
            }
            set {
                this["POWER_ShutdownTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D001")]
        public string MWID {
            get {
                return ((string)(this["MWID"]));
            }
            set {
                this["MWID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11812")]
        public int FROM_MW_PORT {
            get {
                return ((int)(this["FROM_MW_PORT"]));
            }
            set {
                this["FROM_MW_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12012")]
        public int FROM_JSON_PORT {
            get {
                return ((int)(this["FROM_JSON_PORT"]));
            }
            set {
                this["FROM_JSON_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12015")]
        public int FROM_RFID_PORT {
            get {
                return ((int)(this["FROM_RFID_PORT"]));
            }
            set {
                this["FROM_RFID_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9011")]
        public int TO_PAMS_PORT {
            get {
                return ((int)(this["TO_PAMS_PORT"]));
            }
            set {
                this["TO_PAMS_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.30.34.23")]
        public string TO_PAMS_HOST {
            get {
                return ((string)(this["TO_PAMS_HOST"]));
            }
            set {
                this["TO_PAMS_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.200.231")]
        public string TO_CTRL_HOST {
            get {
                return ((string)(this["TO_CTRL_HOST"]));
            }
            set {
                this["TO_CTRL_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20080")]
        public int TO_CTRL_PORT {
            get {
                return ((int)(this["TO_CTRL_PORT"]));
            }
            set {
                this["TO_CTRL_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int CTRL_TIMEOUT {
            get {
                return ((int)(this["CTRL_TIMEOUT"]));
            }
            set {
                this["CTRL_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.200.22")]
        public string TO_MW_HOST {
            get {
                return ((string)(this["TO_MW_HOST"]));
            }
            set {
                this["TO_MW_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11912")]
        public int TO_MW_PORT {
            get {
                return ((int)(this["TO_MW_PORT"]));
            }
            set {
                this["TO_MW_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int MW_TIMEOUT {
            get {
                return ((int)(this["MW_TIMEOUT"]));
            }
            set {
                this["MW_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9100")]
        public int PRT_PORT {
            get {
                return ((int)(this["PRT_PORT"]));
            }
            set {
                this["PRT_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000")]
        public int PRT_TIMEOUT {
            get {
                return ((int)(this["PRT_TIMEOUT"]));
            }
            set {
                this["PRT_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IS_LOGGING_CONNT_HIS {
            get {
                return ((bool)(this["IS_LOGGING_CONNT_HIS"]));
            }
            set {
                this["IS_LOGGING_CONNT_HIS"] = value;
            }
        }
    }
}
