set echo on
spool /data/oracle/admin/RMSORA9I/logs/00_CreateDBFiles.log

CREATE TABLESPACE TS_ADDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_ADDAT01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_CRDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_CRDAT01_01.dbf' SIZE 500M   AUTOEXTEND ON NEXT 100M MAXSIZE 2000M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_DFDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_DFDAT01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_GVDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_GVDAT01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RCDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_RCDAT01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RDDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_RDDAT01_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RDDAT02 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_RDDAT02_01.dbf' SIZE 600M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RFDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_RFDAT01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_SRDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_SRDAT01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_STDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_STDAT01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_STDAT02 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_STDAT02_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_TKDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_TKDAT01_01.dbf' SIZE 800M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_ZZDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_ZZDAT01_01.dbf' SIZE 100M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_MGDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_MGDAT01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_NKDAT01 LOGGING DATAFILE '/oradata/RMSORA9I/DAT/TS_NKDAT01_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_RCLOB01         DATAFILE '/oradata/RMSORA9I/DAT/TS_RCLOB01_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RDLOB01         DATAFILE '/oradata/RMSORA9I/DAT/TS_RDLOB01_01.dbf' SIZE 1500M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_TKLOB01         DATAFILE '/oradata/RMSORA9I/DAT/TS_TKLOB01_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_NKLOB01         DATAFILE '/oradata/RMSORA9I/DAT/TS_NKLOB01_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_ADIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_ADIDX01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_CRIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_CRIDX01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_DFIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_DFIDX01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_GVIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_GVIDX01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RCIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_RCIDX01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RDIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_RDIDX01_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_RFIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_RFIDX01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_SRIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_SRIDX01_01.dbf' SIZE 300M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_STIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_STIDX01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_STIDX02 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_STIDX02_01.dbf' SIZE 1000M  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_TKIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_TKIDX01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_ZZIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_ZZIDX01_01.dbf' SIZE 100M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_MGIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_MGIDX01_01.dbf' SIZE 200M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TS_NKIDX01 LOGGING DATAFILE '/oradata/RMSORA9I/IDX/TS_NKIDX01_01.dbf' SIZE 500M   EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


spool off
