set echo on
spool /data/oracle/admin/RMSORA9I/logs/00_CreateUser.log

CREATE USER RMSDBA01 IDENTIFIED BY RMSDBA01 DEFAULT TABLESPACE TS_RDDAT01 TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO RMSDBA01;

CREATE USER RMSUSR01 IDENTIFIED BY RMSUSR01 DEFAULT TABLESPACE TS_RDDAT01 TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO RMSUSR01;

CREATE USER RMSPDF01 IDENTIFIED BY RMSPDF01 DEFAULT TABLESPACE TS_RDDAT01 TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO RMSPDF01;

spool off
