set echo on
spool /data/oracle/admin/RMSORA9I/logs/02_CreateFK.log
      
ALTER TABLE TB_DFORGTAKEORG ADD (
  CONSTRAINT TB_DFORGTAKEORG_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKOVR_RECORD_CENTER_ID, ORG_TAKE_YYYY, ORG_TAKE_SNO) 
    REFERENCES TB_DFORGTAKE (RECORD_CENTER_ID,TAKOVR_RECORD_CENTER_ID,ORG_TAKE_YYYY,ORG_TAKE_SNO));


ALTER TABLE TB_DFORGTAKOVRORG ADD (
  CONSTRAINT TB_DFORGTAKOVRORG_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKOVR_YYYY, ORG_TAKOVR_SNO) 
    REFERENCES TB_DFORGTAKOVR (RECORD_CENTER_ID,TAKOVR_YYYY,ORG_TAKOVR_SNO));


ALTER TABLE TB_RDREADDOCFOLDER ADD (
  CONSTRAINT TB_RDREADDOCFOLDER_FK01 FOREIGN KEY (RECORD_CENTER_ID, READ_DOC_SEQ, READ_DOC_NO) 
    REFERENCES TB_RDREADDOC (RECORD_CENTER_ID,READ_DOC_SEQ,READ_DOC_NO));


ALTER TABLE TB_STQNA ADD (
  CONSTRAINT TB_STQNA_FK01 FOREIGN KEY (REF_BOARD_SNO) 
    REFERENCES TB_STQNA (BOARD_SNO));


ALTER TABLE TB_STRECORDCHRGR ADD (
  CONSTRAINT TB_STRECORDCHRGR_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_TKFOLDERATTACHFILE ADD (
  CONSTRAINT TB_TKFOLDERATTACHFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERCHNGHIST ADD (
  CONSTRAINT TB_TKFOLDERCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERCREAT ADD (
  CONSTRAINT TB_TKFOLDERCREAT_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERERROR ADD (
  CONSTRAINT TB_TKFOLDERERROR_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERPJTCLSS ADD (
  CONSTRAINT TB_TKFOLDERPJTCLSS_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERREADRANG ADD (
  CONSTRAINT TB_TKFOLDERREADRANG_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERREL ADD (
  CONSTRAINT TB_TKFOLDERREL_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKFOLDERTAKETAKOVR ADD (
  CONSTRAINT TB_TKFOLDERTAKETAKOVR_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKMONITOR ADD (
  CONSTRAINT TB_TKMONITOR_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_TKMONITORFILE ADD (
  CONSTRAINT TB_TKMONITORFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, MONITOR_ID) 
    REFERENCES TB_TKMONITOR (RECORD_CENTER_ID,MONITOR_ID));


ALTER TABLE TB_TKMONITORINFO ADD (
  CONSTRAINT TB_TKMONITORINFO_FK01 FOREIGN KEY (RECORD_CENTER_ID, MONITOR_ID) 
    REFERENCES TB_TKMONITOR (RECORD_CENTER_ID,MONITOR_ID));


ALTER TABLE TB_TKRECORD ADD (
  CONSTRAINT TB_TKRECORD_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKRECORDCHNGHIST ADD (
  CONSTRAINT TB_TKRECORDCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKRECORDCREAT ADD (
  CONSTRAINT TB_TKRECORDCREAT_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKRECORDERROR ADD (
  CONSTRAINT TB_TKRECORDERROR_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKRECORDINFOSRC ADD (
  CONSTRAINT TB_TKRECORDINFOSRC_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKRECORDREADRANG ADD (
  CONSTRAINT TB_TKRECORDREADRANG_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKRECORDREG ADD (
  CONSTRAINT TB_TKRECORDREG_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_REG_TAKE_NO) 
    REFERENCES TB_TKFOLDERREG (RECORD_CENTER_ID,FOLDER_REG_TAKE_NO));


ALTER TABLE TB_TKRECORDREGFILE ADD (
  CONSTRAINT TB_TKRECORDREGFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_REG_SEQ) 
    REFERENCES TB_TKRECORDREG (RECORD_CENTER_ID,RECORD_REG_SEQ));


ALTER TABLE TB_TKRECORDREL ADD (
  CONSTRAINT TB_TKRECORDREL_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKREVALHIST ADD (
  CONSTRAINT TB_TKREVALHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKSPCLLIST ADD (
  CONSTRAINT TB_TKSPCLLIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));

ALTER TABLE TB_TKSPCLLIST ADD (
  CONSTRAINT TB_TKSPCLLIST_FK02 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_ZZCLSS ADD (
  CONSTRAINT TB_ZZCLSS_FK01 FOREIGN KEY (UPPER_CLSS_CD) 
    REFERENCES TB_ZZCLSS (CLSS_CD));


ALTER TABLE TB_ZZPJTCLSSHIST ADD (
  CONSTRAINT TB_ZZPJTCLSSHIST_FK01 FOREIGN KEY (PJT_CLSS_ID) 
    REFERENCES TB_ZZPJTCLSS (PJT_CLSS_ID));


ALTER TABLE TB_ZZPJTTYPEMAPPNG ADD (
  CONSTRAINT TB_ZZPJTTYPEMAPPNG_FK01 FOREIGN KEY (PJT_CLSS_ID) 
    REFERENCES TB_ZZPJTCLSS (PJT_CLSS_ID));


ALTER TABLE TB_ZZSENDUNITORG ADD (
  CONSTRAINT TB_ZZSENDUNITORG_FK01 FOREIGN KEY (TRANS_UNIT_CD) 
    REFERENCES TB_ZZSENDUNIT (TRANS_UNIT_CD));


ALTER TABLE TB_ZZUNITCHNGHIST ADD (
  CONSTRAINT TB_ZZUNITCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, UNIT_CD) 
    REFERENCES TB_ZZUNIT (RECORD_CENTER_ID,UNIT_CD));


ALTER TABLE TB_ZZUNITPRESVTERMHIST ADD (
  CONSTRAINT TB_ZZUNITPRESVTERMHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, UNIT_CD) 
    REFERENCES TB_ZZUNIT (RECORD_CENTER_ID,UNIT_CD));


ALTER TABLE TB_CRFOLDER ADD (
  CONSTRAINT TB_CRFOLDER_FK01 FOREIGN KEY (RECORD_CENTER_ID, CR_REPORT_YYYY, CR_REPORT_ORG_CD, CREAT_SYS_CD, CR_REPORT_SNO) 
    REFERENCES TB_CRREPORT (RECORD_CENTER_ID,CR_REPORT_YYYY,CR_REPORT_ORG_CD,CREAT_SYS_CD,CR_REPORT_SNO));


ALTER TABLE TB_CRFOLDERCHNGHIST ADD (
  CONSTRAINT TB_CRFOLDERCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_RECV_SEQ) 
    REFERENCES TB_CRFOLDER (RECORD_CENTER_ID,FOLDER_RECV_SEQ));


ALTER TABLE TB_CRFOLDERTAKETAKOVR ADD (
  CONSTRAINT TB_CRFOLDERTAKETAKOVR_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_RECV_SEQ) 
    REFERENCES TB_CRFOLDER (RECORD_CENTER_ID,FOLDER_RECV_SEQ));


ALTER TABLE TB_CRRECORD ADD (
  CONSTRAINT TB_CRRECORD_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_RECV_SEQ) 
    REFERENCES TB_CRFOLDER (RECORD_CENTER_ID,FOLDER_RECV_SEQ));


ALTER TABLE TB_CRRECORDCHNGHIST ADD (
  CONSTRAINT TB_CRRECORDCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_RECV_SEQ) 
    REFERENCES TB_CRRECORD (RECORD_CENTER_ID,RECORD_RECV_SEQ));


ALTER TABLE TB_CRSPCLLIST ADD (
  CONSTRAINT TB_CRSPCLLIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_RECV_SEQ) 
    REFERENCES TB_CRFOLDER (RECORD_CENTER_ID,FOLDER_RECV_SEQ));

ALTER TABLE TB_CRSPCLLIST ADD (
  CONSTRAINT TB_CRSPCLLIST_FK02 FOREIGN KEY (RECORD_CENTER_ID, RECORD_RECV_SEQ) 
    REFERENCES TB_CRRECORD (RECORD_CENTER_ID,RECORD_RECV_SEQ));


ALTER TABLE TB_DFRECVTRANSFLIST ADD (
  CONSTRAINT TB_DFRECVTRANSFLIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO) 
    REFERENCES TB_DFTRANSFWORK (RECORD_CENTER_ID,TRANSF_YYYY,TRANSF_GRP_SNO));


ALTER TABLE TB_RDTAKETAKOVRCLSS ADD (
  CONSTRAINT TB_RDTAKETAKOVRCLSS_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKE_TAKOVR_DIV_CD, TAKE_TAKOVR_REP_ORG_CD, TAKE_TAKOVR_YYYY, TAKE_TAKOVR_SNO) 
    REFERENCES TB_RDTAKETAKOVRPLAN (RECORD_CENTER_ID,TAKE_TAKOVR_DIV_CD,TAKE_TAKOVR_REP_ORG_CD,TAKE_TAKOVR_YYYY,TAKE_TAKOVR_SNO));


ALTER TABLE TB_RDTAKETAKOVRLIST ADD (
  CONSTRAINT TB_RDTAKETAKOVRLIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKE_TAKOVR_DIV_CD, TAKE_TAKOVR_REP_ORG_CD, TAKE_TAKOVR_YYYY, TAKE_TAKOVR_SNO) 
    REFERENCES TB_RDTAKETAKOVRPLAN (RECORD_CENTER_ID,TAKE_TAKOVR_DIV_CD,TAKE_TAKOVR_REP_ORG_CD,TAKE_TAKOVR_YYYY,TAKE_TAKOVR_SNO));


ALTER TABLE TB_SRBOOKSF ADD (
  CONSTRAINT TB_SRBOOKSF_FK01 FOREIGN KEY (RECORD_CENTER_ID, STAKRM_ID) 
    REFERENCES TB_SRSTAKRM (RECORD_CENTER_ID,STAKRM_ID));


ALTER TABLE TB_SRMFBOOKSF ADD (
  CONSTRAINT TB_SRMFBOOKSF_FK01 FOREIGN KEY (RECORD_CENTER_ID, MF_STAKRM_ID) 
    REFERENCES TB_SRMFSTAKRM (RECORD_CENTER_ID,MF_STAKRM_ID));


ALTER TABLE TB_SRMFPIC ADD (
  CONSTRAINT TB_SRMFPIC_FK01 FOREIGN KEY (RECORD_CENTER_ID, MF_STAKRM_ID, MF_BOOKSF_ID) 
    REFERENCES TB_SRMFBOOKSF (RECORD_CENTER_ID,MF_STAKRM_ID,MF_BOOKSF_ID));


ALTER TABLE TB_SRPRESVBOX ADD (
  CONSTRAINT TB_SRPRESVBOX_FK01 FOREIGN KEY (RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID) 
    REFERENCES TB_SRBOOKSF (RECORD_CENTER_ID,STAKRM_ID,BOOKSF_ID));


ALTER TABLE TB_STCOMPUEQUIP ADD (
  CONSTRAINT TB_STCOMPUEQUIP_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_STCONFIG ADD (
  CONSTRAINT TB_STCONFIG_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_STDISINF ADD (
  CONSTRAINT TB_STDISINF_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_STMEDIUM ADD (
  CONSTRAINT TB_STMEDIUM_FK01 FOREIGN KEY (RECORD_CENTER_ID, VOLM_ID) 
    REFERENCES TB_STVOLM (RECORD_CENTER_ID,VOLM_ID));


ALTER TABLE TB_STMENU ADD (
  CONSTRAINT TB_STMENU_FK01 FOREIGN KEY (RECORD_CENTER_ID, UPPER_MENU_ID) 
    REFERENCES TB_STMENU (RECORD_CENTER_ID,MENU_ID));

ALTER TABLE TB_STMENU ADD (
  CONSTRAINT TB_STMENU_FK02 FOREIGN KEY (MENU_LINK_SNO) 
    REFERENCES TB_STMENULINK (MENU_LINK_SNO));


ALTER TABLE TB_STORG ADD (
  CONSTRAINT TB_STORG_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_STORIGNFILE ADD (
  CONSTRAINT TB_STORIGNFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, MEDIUM_ID) 
    REFERENCES TB_STMEDIUM (RECORD_CENTER_ID, MEDIUM_ID));

ALTER TABLE TB_STORIGNFILEHIST ADD (
  CONSTRAINT TB_STORIGNFILEHIST_FK01 FOREIGN KEY (ORIGN_ID)
    REFERENCES TB_STRECORDORIGNHIST (ORIGN_ID));

ALTER TABLE TB_STORIGNPAGEHIST ADD (
  CONSTRAINT TB_STORIGNPAGEHIST_FK02 FOREIGN KEY (ORIGN_FILE_ID)
    REFERENCES TB_STORIGNFILEHIST(ORIGN_FILE_ID));


ALTER TABLE TB_STORIGNNEOFILE ADD (
  CONSTRAINT TB_STORIGNNEOFILE_FK01 FOREIGN KEY (ORIGN_ID) 
    REFERENCES TB_STRECORDORIGN (ORIGN_ID));

ALTER TABLE TB_STORIGNNEOFILE ADD (
  CONSTRAINT TB_STORIGNNEOFILE_FK02 FOREIGN KEY (RECORD_CENTER_ID, MEDIUM_ID) 
    REFERENCES TB_STMEDIUM (RECORD_CENTER_ID,MEDIUM_ID));


ALTER TABLE TB_STORIGNPAGE ADD (
  CONSTRAINT TB_STORIGNPAGE_FK01 FOREIGN KEY (ORIGN_FILE_ID) 
    REFERENCES TB_STORIGNFILE (ORIGN_FILE_ID));


ALTER TABLE TB_STORIGNPDFA1FILE ADD (
  CONSTRAINT TB_STORIGNPDFA1FILE_FK01 FOREIGN KEY (ORIGN_ID) 
    REFERENCES TB_STRECORDORIGN (ORIGN_ID));

ALTER TABLE TB_STORIGNPDFA1FILE ADD (
  CONSTRAINT TB_STORIGNPDFA1FILE_FK02 FOREIGN KEY (RECORD_CENTER_ID, MEDIUM_ID) 
    REFERENCES TB_STMEDIUM (RECORD_CENTER_ID,MEDIUM_ID));


ALTER TABLE TB_STORIGNPDFA1PAGE ADD (
  CONSTRAINT TB_STORIGNPDFA1PAGE_FK01 FOREIGN KEY (PDF_A1_FILE_ID) 
    REFERENCES TB_STORIGNPDFA1FILE (PDF_A1_FILE_ID));


ALTER TABLE TB_STPRESVEQUIP ADD (
  CONSTRAINT TB_STPRESVEQUIP_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));


ALTER TABLE TB_STUSERGRPMENU ADD (
  CONSTRAINT TB_STUSERGRPMENU_FK01 FOREIGN KEY (RECORD_CENTER_ID, GRANT_GRP_CD) 
    REFERENCES TB_STGRANTGRP (RECORD_CENTER_ID,GRANT_GRP_CD));

ALTER TABLE TB_STUSERGRPMENU ADD (
  CONSTRAINT TB_STUSERGRPMENU_FK02 FOREIGN KEY (RECORD_CENTER_ID, MENU_ID) 
    REFERENCES TB_STMENU (RECORD_CENTER_ID,MENU_ID));


ALTER TABLE TB_TKATTACHFILE ADD (
  CONSTRAINT TB_TKATTACHFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKBATCHTAKEERROR ADD (
  CONSTRAINT TB_TKBATCHTAKEERROR_FK01 FOREIGN KEY (RECORD_CENTER_ID, BATCH_REG_DTIME) 
    REFERENCES TB_TKBATCHTAKELOG (RECORD_CENTER_ID,BATCH_REG_DTIME));


ALTER TABLE TB_TKDISUSEHIST ADD (
  CONSTRAINT TB_TKDISUSEHISTT_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_TAKE_SEQ) 
    REFERENCES TB_TKFOLDER (RECORD_CENTER_ID,FOLDER_TAKE_SEQ));


ALTER TABLE TB_TKOPENHIST ADD (
  CONSTRAINT TB_TKOPENHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKOPENRESORT ADD (
  CONSTRAINT TB_TKOPENRESORT_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKOPENREVW ADD (
  CONSTRAINT TB_TKOPENREVW_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ) 
    REFERENCES TB_TKRECORD (RECORD_CENTER_ID,RECORD_TAKE_SEQ));


ALTER TABLE TB_TKORGTAKEERROR ADD (
  CONSTRAINT TB_TKORGTAKEERROR_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKE_YYYY, TAKE_ORG_CD, CREAT_SYS_CD, TAKE_SNO) 
    REFERENCES TB_TKORGTAKEPLAN (RECORD_CENTER_ID,TAKE_YYYY,TAKE_ORG_CD,CREAT_SYS_CD,TAKE_SNO));

ALTER TABLE TB_TKVIRUSCHECK ADD
(
	CONSTRAINT TB_TKVIRUSCHECK_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ, ATTACH_FILE_TYPE, REG_SEQ)
	REFERENCES TB_TKATTACHFILE (RECORD_CENTER_ID, RECORD_TAKE_SEQ, ATTACH_FILE_TYPE, REG_SEQ)
);

ALTER TABLE TB_ZZBISCLSS ADD (
  CONSTRAINT TB_ZZBISCLSS_FK02 FOREIGN KEY (TRANS_UNIT_CD) 
    REFERENCES TB_ZZSENDUNIT (TRANS_UNIT_CD));


ALTER TABLE TB_ZZBISCLSSCHNG ADD (
  CONSTRAINT TB_ZZBISCLSSCHNG_FK01 FOREIGN KEY (BIS_CLSS_ID) 
    REFERENCES TB_ZZBISCLSS (BIS_CLSS_ID));


ALTER TABLE TB_ZZBISCLSSHIST ADD (
  CONSTRAINT TB_ZZBISCLSSHIST_FK01 FOREIGN KEY (BIS_CLSS_ID) 
    REFERENCES TB_ZZBISCLSS (BIS_CLSS_ID));


ALTER TABLE TB_ZZBISCLSSRELLAW ADD (
  CONSTRAINT TB_ZZBISCLSSRELLAW_FK01 FOREIGN KEY (BIS_CLSS_ID) 
    REFERENCES TB_ZZBISCLSS (BIS_CLSS_ID));


ALTER TABLE TB_ZZBISORG ADD (
  CONSTRAINT TB_ZZBISORG_FK01 FOREIGN KEY (BIS_CLSS_ID) 
    REFERENCES TB_ZZBISCLSS (BIS_CLSS_ID));


ALTER TABLE TB_ZZCOMCD ADD (
  CONSTRAINT TB_ZZCOMCD_FK01 FOREIGN KEY (COM_TYPE_CD) 
    REFERENCES TB_ZZCOMTYPECD (COM_TYPE_CD));


ALTER TABLE TB_ZZORGUNIT ADD (
  CONSTRAINT TB_ZZORGUNIT_FK01 FOREIGN KEY (RECORD_CENTER_ID, ORG_CD) 
    REFERENCES TB_STORG (RECORD_CENTER_ID,ORG_CD));

ALTER TABLE TB_ZZORGUNIT ADD (
  CONSTRAINT TB_ZZORGUNIT_FK02 FOREIGN KEY (RECORD_CENTER_ID, UNIT_CD) 
    REFERENCES TB_ZZUNIT (RECORD_CENTER_ID,UNIT_CD));


ALTER TABLE TB_ZZORGUNITWORKHIST ADD (
  CONSTRAINT TB_ZZORGUNITWORKHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, ORG_CD, UNIT_CD) 
    REFERENCES TB_ZZORGUNIT (RECORD_CENTER_ID,ORG_CD,UNIT_CD));


ALTER TABLE TB_ZZPJTMAPPNG ADD (
  CONSTRAINT TB_ZZPJTMAPPNG_FK01 FOREIGN KEY (PJT_CLSS_ID) 
    REFERENCES TB_ZZPJTCLSS (PJT_CLSS_ID));

ALTER TABLE TB_ZZPJTMAPPNG ADD (
  CONSTRAINT TB_ZZPJTMAPPNG_FK02 FOREIGN KEY (BIS_CLSS_ID) 
    REFERENCES TB_ZZBISCLSS (BIS_CLSS_ID));


ALTER TABLE TB_ZZPRESVTERMHIST ADD (
  CONSTRAINT TB_ZZPRESVTERMHIST_FK01 FOREIGN KEY (BIS_CLSS_ID) 
    REFERENCES TB_ZZBISCLSS (BIS_CLSS_ID));


ALTER TABLE TB_ZZSTNDMNG ADD (
  CONSTRAINT TB_ZZSTNDMNG_FK01 FOREIGN KEY (RECORD_CENTER_ID, STND_MNG_TYPE_CD) 
    REFERENCES TB_ZZSTNDMNGTYPE (RECORD_CENTER_ID,STND_MNG_TYPE_CD));


ALTER TABLE TB_ZZUNITCHNGREQ ADD (
  CONSTRAINT TB_ZZUNITCHNGREQ_FK01 FOREIGN KEY (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD) 
    REFERENCES TB_ZZUNITREQ (RECORD_CENTER_ID,REQ_SNO_ID,UNIT_REQ_TYPE_CD));

ALTER TABLE TB_ZZUNITCHNGREQ ADD (
  CONSTRAINT TB_ZZUNITCHNGREQ_FK02 FOREIGN KEY (RECORD_CENTER_ID, ORG_CD, UNIT_CD) 
    REFERENCES TB_ZZORGUNIT (RECORD_CENTER_ID,ORG_CD,UNIT_CD));


ALTER TABLE TB_ZZUNITMOVREQ ADD (
  CONSTRAINT TB_ZZUNITMOVREQ_FK01 FOREIGN KEY (RECORD_CENTER_ID, CHNG_BEF_ORG_CD) 
    REFERENCES TB_STORG (RECORD_CENTER_ID,ORG_CD));

ALTER TABLE TB_ZZUNITMOVREQ ADD (
  CONSTRAINT TB_ZZUNITMOVREQ_FK02 FOREIGN KEY (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD) 
    REFERENCES TB_ZZUNITREQ (RECORD_CENTER_ID,REQ_SNO_ID,UNIT_REQ_TYPE_CD));

ALTER TABLE TB_ZZUNITMOVREQ ADD (
  CONSTRAINT TB_ZZUNITMOVREQ_FK03 FOREIGN KEY (RECORD_CENTER_ID, CHNG_AFT_ORG_CD) 
    REFERENCES TB_STORG (RECORD_CENTER_ID,ORG_CD));


ALTER TABLE TB_ZZUNITNEWREQ ADD (
  CONSTRAINT TB_ZZUNITNEWREQ_FK01 FOREIGN KEY (CLSS_CD) 
    REFERENCES TB_ZZCLSS (CLSS_CD));

ALTER TABLE TB_ZZUNITNEWREQ ADD (
  CONSTRAINT TB_ZZUNITNEWREQ_FK02 FOREIGN KEY (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD) 
    REFERENCES TB_ZZUNITREQ (RECORD_CENTER_ID,REQ_SNO_ID,UNIT_REQ_TYPE_CD));


ALTER TABLE TB_CRATTACHFILE ADD (
  CONSTRAINT TB_CRATTACHFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_RECV_SEQ) 
    REFERENCES TB_CRRECORD (RECORD_CENTER_ID,RECORD_RECV_SEQ));


ALTER TABLE TB_RDFOLDER ADD (
  CONSTRAINT TB_RDFOLDER_FK01 FOREIGN KEY (RECORD_CENTER_ID, PRESV_BOX_ID) 
    REFERENCES TB_SRPRESVBOX (RECORD_CENTER_ID, PRESV_BOX_ID));

ALTER TABLE TB_RDFOLDER ADD (
  CONSTRAINT TB_RDFOLDER_FK02 FOREIGN KEY (RECORD_CENTER_ID, TAKOVR_RECORD_CENTER_ID, ORG_TAKE_YYYY, ORG_TAKE_SNO) 
    REFERENCES TB_DFORGTAKE (RECORD_CENTER_ID,TAKOVR_RECORD_CENTER_ID,ORG_TAKE_YYYY,ORG_TAKE_SNO));


ALTER TABLE TB_RDFOLDERACCS ADD (
  CONSTRAINT TB_RDFOLDERACCS_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERCHNGHIST ADD (
  CONSTRAINT TB_RDFOLDERCHNGHIST_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERCREAT ADD (
  CONSTRAINT TB_RDFOLDERCREAT_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERKEYWD ADD (
  CONSTRAINT TB_RDFOLDERKEYWD_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERPJTCLSS ADD (
  CONSTRAINT TB_RDFOLDERPJTCLSS_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERREADDETL ADD (
  CONSTRAINT TB_RDFOLDERREADDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, READ_REQNO) 
    REFERENCES TB_RDREADREQ (RECORD_CENTER_ID,READ_REQNO));


ALTER TABLE TB_RDFOLDERREADRANG ADD (
  CONSTRAINT TB_RDFOLDERREADRANG_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERREL ADD (
  CONSTRAINT TB_RDFOLDERREL_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDFOLDERTAKETAKOVR ADD (
  CONSTRAINT TB_RDFOLDERTAKETAKOVR_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDRECORD ADD (
  CONSTRAINT TB_RDRECORD_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_RDRECORDACCS ADD (
  CONSTRAINT TB_RDRECORDACCS_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDRECORDCHNGHIST ADD (
  CONSTRAINT TB_RDRECORDCHNGHIST_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDRECORDCREAT ADD (
  CONSTRAINT TB_RDRECORDCREAT_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDRECORDINFOSRC ADD (
  CONSTRAINT TB_RDRECORDINFOSRC_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDRECORDKEYWD ADD (
  CONSTRAINT TB_RDRECORDKEYWD_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDRECORDREADDETL ADD (
  CONSTRAINT TB_RDRECORDREADDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, READ_REQNO) 
    REFERENCES TB_RDREADREQ (RECORD_CENTER_ID,READ_REQNO));


ALTER TABLE TB_RDRECORDREADRANG ADD (
  CONSTRAINT TB_RDRECORDREADRANG_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDRECORDREL ADD (
  CONSTRAINT TB_RDRECORDREL_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));

ALTER TABLE TB_RDRECORDTITLEHIST ADD (
  CONSTRAINT  TB_RDRECORDTITLEHIST_FK01 FOREIGN KEY (RECORD_ID)
    REFERENCES TB_RDRECORD(RECORD_ID));


ALTER TABLE TB_SRBOOKSFARNGDETL ADD (
  CONSTRAINT TB_SRBOOKSFARNGDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, BOOKSF_ARNG_ID) 
    REFERENCES TB_SRBOOKSFARNG (RECORD_CENTER_ID,BOOKSF_ARNG_ID));

ALTER TABLE TB_SRBOOKSFARNGDETL ADD (
  CONSTRAINT TB_SRBOOKSFARNGDETL_FK02 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_SRBOOKSFARNGDETL ADD (
  CONSTRAINT TB_SRBOOKSFARNGDETL_FK03 FOREIGN KEY (RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID) 
    REFERENCES TB_SRBOOKSF (RECORD_CENTER_ID,STAKRM_ID,BOOKSF_ID));


ALTER TABLE TB_SRCNTCHKDETL ADD (
  CONSTRAINT TB_SRCNTCHKDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, CNTCHK_ID) 
    REFERENCES TB_SRCNTCHK (RECORD_CENTER_ID,CNTCHK_ID));

ALTER TABLE TB_SRCNTCHKDETL ADD (
  CONSTRAINT TB_SRCNTCHKDETL_FK02 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_SRCNTCHKDETL ADD (
  CONSTRAINT TB_SRCNTCHKDETL_FK03 FOREIGN KEY (RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID) 
    REFERENCES TB_SRBOOKSF (RECORD_CENTER_ID,STAKRM_ID,BOOKSF_ID));


ALTER TABLE TB_SRINOUTFOLDER ADD (
  CONSTRAINT TB_SRINOUTFOLDER_FK01 FOREIGN KEY (RECORD_CENTER_ID, OUT_ID) 
    REFERENCES TB_SROUT (RECORD_CENTER_ID,OUT_ID));

ALTER TABLE TB_SRINOUTFOLDER ADD (
  CONSTRAINT TB_SRINOUTFOLDER_FK02 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_SRINOUTFOLDER ADD (
  CONSTRAINT TB_SRINOUTFOLDER_FK03 FOREIGN KEY (RECORD_CENTER_ID, IN_ID) 
    REFERENCES TB_SRIN (RECORD_CENTER_ID,IN_ID));


ALTER TABLE TB_SRMFCOPY ADD (
  CONSTRAINT TB_SRMFCOPY_FK01 FOREIGN KEY (RECORD_CENTER_ID, PIC_SNO) 
    REFERENCES TB_SRMFPIC (RECORD_CENTER_ID,PIC_SNO));


ALTER TABLE TB_SRMFPICDETL ADD (
  CONSTRAINT TB_SRMFPICDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, PIC_SNO) 
    REFERENCES TB_SRMFPIC (RECORD_CENTER_ID,PIC_SNO));


ALTER TABLE TB_SROPTIDISKDETL ADD (
  CONSTRAINT TB_SROPTIDISKDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, OPTI_DISK_ID) 
    REFERENCES TB_SROPTIDISK (RECORD_CENTER_ID, OPTI_DISK_ID));


ALTER TABLE TB_STCREATSYS ADD (
  CONSTRAINT TB_STCREATSYS_FK01 FOREIGN KEY (RECORD_CENTER_ID, ORG_CD) 
    REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD));


ALTER TABLE TB_STDEPT ADD (
  CONSTRAINT TB_STDEPT_FK01 FOREIGN KEY (RECORD_CENTER_ID, ORG_CD) 
    REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD));


ALTER TABLE TB_STFOLDERNEOFILE ADD (
  CONSTRAINT TB_STFOLDERNEOFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, MEDIUM_ID) 
    REFERENCES TB_STMEDIUM (RECORD_CENTER_ID, MEDIUM_ID));


ALTER TABLE TB_STINFOFILE ADD (
  CONSTRAINT TB_STINFOFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, MEDIUM_ID) 
    REFERENCES TB_STMEDIUM (RECORD_CENTER_ID, MEDIUM_ID));


ALTER TABLE TB_STSTAKRMINFO ADD (
  CONSTRAINT TB_STSTAKRMINFO_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));

ALTER TABLE TB_STSTAKRMINFO ADD (
  CONSTRAINT TB_STSTAKRMINFO_FK02 FOREIGN KEY (INFO_FILE_ID) 
    REFERENCES TB_STINFOFILE (INFO_FILE_ID));


ALTER TABLE TB_STUSER ADD (
  CONSTRAINT TB_STUSER_FK01 FOREIGN KEY (RECORD_CENTER_ID) 
    REFERENCES TB_STRECORDCENTER (RECORD_CENTER_ID));

ALTER TABLE TB_STUSER ADD (
  CONSTRAINT TB_STUSER_FK02 FOREIGN KEY (DEPT_CD) 
    REFERENCES TB_STDEPT (DEPT_CD));


ALTER TABLE TB_STUSERGRP ADD (
  CONSTRAINT TB_STUSERGRP_FK01 FOREIGN KEY (USER_ID) 
    REFERENCES TB_STUSER (USER_ID));

ALTER TABLE TB_STUSERGRP ADD (
  CONSTRAINT TB_STUSERGRP_FK02 FOREIGN KEY (RECORD_CENTER_ID, GRANT_GRP_CD) 
    REFERENCES TB_STGRANTGRP (RECORD_CENTER_ID, GRANT_GRP_CD));


ALTER TABLE TB_STUSERLOGIN ADD (
  CONSTRAINT TB_STUSERLOGIN_FK01 FOREIGN KEY (USER_ID) 
    REFERENCES TB_STUSER (USER_ID));


ALTER TABLE TB_STUSERMENUGRANT ADD (
  CONSTRAINT TB_STUSERMENUGRANT_FK01 FOREIGN KEY (USER_ID) 
    REFERENCES TB_STUSER (USER_ID));

ALTER TABLE TB_STUSERMENUGRANT ADD (
  CONSTRAINT TB_STUSERMENUGRANT_FK02 FOREIGN KEY (RECORD_CENTER_ID, MENU_ID) 
    REFERENCES TB_STMENU (RECORD_CENTER_ID, MENU_ID));


ALTER TABLE TB_ZZORGCOMSTND ADD (
  CONSTRAINT TB_ZZORGCOMSTND_FK01 FOREIGN KEY (RECORD_CENTER_ID, STND_MNG_TYPE_CD, VER) 
    REFERENCES TB_ZZSTNDMNG (RECORD_CENTER_ID, STND_MNG_TYPE_CD, VER));


ALTER TABLE TB_ZZPRESVTERMRULE ADD (
  CONSTRAINT TB_ZZPRESVTERMRULE_FK01 FOREIGN KEY (RECORD_CENTER_ID, STND_MNG_TYPE_CD, VER) 
    REFERENCES TB_ZZSTNDMNG (RECORD_CENTER_ID, STND_MNG_TYPE_CD, VER));


ALTER TABLE TB_DFDISUSEHIST ADD (
  CONSTRAINT TB_DFDISUSEHIST_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_DFDISUSEHIST ADD (
  CONSTRAINT TB_DFDISUSEHIST_FK02 FOREIGN KEY (RECORD_CENTER_ID, EVAL_DISCU_NO) 
    REFERENCES TB_DFDISUSEDISCU (RECORD_CENTER_ID, EVAL_DISCU_NO));


ALTER TABLE TB_DFORGTAKOVRLIST ADD (
  CONSTRAINT TB_DFORGTAKOVRLIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKOVR_YYYY, ORG_TAKOVR_SNO, ORG_CD, CLSS_DIV_CD, CLSS_ID) 
    REFERENCES TB_DFORGTAKOVRORG (RECORD_CENTER_ID, TAKOVR_YYYY, ORG_TAKOVR_SNO, ORG_CD, CLSS_DIV_CD, CLSS_ID));

ALTER TABLE TB_DFORGTAKOVRLIST ADD (
  CONSTRAINT TB_DFORGTAKOVRLIST_FK02 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));


ALTER TABLE TB_DFREVALHIST ADD (
  CONSTRAINT TB_DFREVALHIST_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_DFREVALHIST ADD (
  CONSTRAINT TB_DFREVALHIST_FK02 FOREIGN KEY (RECORD_CENTER_ID, EVAL_DISCU_NO) 
    REFERENCES TB_DFREVALDISCU (RECORD_CENTER_ID, EVAL_DISCU_NO));


ALTER TABLE TB_DFTRANSFHIST ADD (
  CONSTRAINT TB_DFTRANSFHIST_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_DFTRANSFHIST ADD (
  CONSTRAINT TB_DFTRANSFHIST_FK02 FOREIGN KEY (RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO) 
    REFERENCES TB_DFTRANSFWORK (RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO));


ALTER TABLE TB_RDOPENHIST ADD (
  CONSTRAINT TB_RDOPENHIST_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDOPENRESORT ADD (
  CONSTRAINT TB_RDOPENRESORT_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_RDOPENREVW ADD (
  CONSTRAINT TB_RDOPENREVW_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));


ALTER TABLE TB_STFOLDERQUERY ADD (
  CONSTRAINT TB_STFOLDERQUERY_FK01 FOREIGN KEY (USER_ID) 
    REFERENCES TB_STUSER (USER_ID));


ALTER TABLE TB_STRECORDQUERY ADD (
  CONSTRAINT TB_STRECORDQUERY_FK01 FOREIGN KEY (USER_ID) 
    REFERENCES TB_STUSER (USER_ID));


ALTER TABLE TB_DFDISUSEEVAL ADD (
  CONSTRAINT TB_DFDISUSEEVAL_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID, DISUSE_YYYY) 
    REFERENCES TB_DFDISUSEHIST (RECORD_CENTER_ID, FOLDER_ID, DISUSE_YYYY));


ALTER TABLE TB_DFREVALEVAL ADD (
  CONSTRAINT TB_DFREVALEVAL_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID, REVAL_SEQ) 
    REFERENCES TB_DFREVALHIST (RECORD_CENTER_ID, FOLDER_ID, REVAL_SEQ));


ALTER TABLE TB_RDOPENEVAL ADD (
  CONSTRAINT TB_RDOPENEVAL_FK01 FOREIGN KEY (RECORD_ID, DISCU_SEQ) 
    REFERENCES TB_RDOPENREVW (RECORD_ID, DISCU_SEQ));

ALTER TABLE TB_TKVERDOC_FILE ADD (
  CONSTRAINT TB_TKVERDOC_FILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, TAKE_YYYY, TAKE_MM) 
    REFERENCES TB_TKVERDOC_PLAN (RECORD_CENTER_ID, TAKE_YYYY, TAKE_MM));


ALTER TABLE TB_ZZUNITDELREQ ADD (
  CONSTRAINT TB_ZZUNITDELREQ_FK01 FOREIGN KEY (RECORD_CENTER_ID, CHNG_BEF_ORG_CD) 
 REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD),
  CONSTRAINT TB_ZZUNITDELREQ_FK02 FOREIGN KEY (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD) 
 REFERENCES TB_ZZUNITREQ (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD),
  CONSTRAINT TB_ZZUNITDELREQ_FK04 FOREIGN KEY (RECORD_CENTER_ID, CHNG_BEF_ORG_CD, CHNG_BEF_UNIT_CD) 
 REFERENCES TB_ZZORGUNIT (RECORD_CENTER_ID, ORG_CD, UNIT_CD));
 
ALTER TABLE TB_ZZUNITMOVEREQ ADD (
  CONSTRAINT TB_ZZUNITMOVEREQ_FK01 FOREIGN KEY (RECORD_CENTER_ID, CHNG_BEF_ORG_CD) 
 REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD),
  CONSTRAINT TB_ZZUNITMOVEREQ_FK02 FOREIGN KEY (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD) 
 REFERENCES TB_ZZUNITREQ (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD),
  CONSTRAINT TB_ZZUNITMOVEREQ_FK03 FOREIGN KEY (RECORD_CENTER_ID, CHNG_AFT_ORG_CD) 
 REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD),
  CONSTRAINT TB_ZZUNITMOVEREQ_FK04 FOREIGN KEY (RECORD_CENTER_ID, CHNG_BEF_ORG_CD, CHNG_BEF_UNIT_CD) 
 REFERENCES TB_ZZORGUNIT (RECORD_CENTER_ID, ORG_CD, UNIT_CD));

ALTER TABLE TB_ZZUNITSETREQ ADD (
  CONSTRAINT TB_ZZUNITSETREQ_FK01 FOREIGN KEY (RECORD_CENTER_ID, CHNG_BEF_ORG_CD) 
 REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD),
  CONSTRAINT TB_ZZUNITSETREQ_FK02 FOREIGN KEY (RECORD_CENTER_ID, REQ_SNO_ID, UNIT_REQ_TYPE_CD) 
 REFERENCES TB_ZZUNITREQ (RECORD_CENTER_ID,REQ_SNO_ID,UNIT_REQ_TYPE_CD),
  CONSTRAINT TB_ZZUNITSETREQ_FK03 FOREIGN KEY (RECORD_CENTER_ID, CHNG_AFT_ORG_CD) 
 REFERENCES TB_STORG (RECORD_CENTER_ID, ORG_CD));



ALTER TABLE TB_RDOPENRESORTOPIN ADD (
  CONSTRAINT TB_RDOPENRESORTOPIN_FK01 FOREIGN KEY (RECORD_ID)
 REFERENCES TB_RDRECORD (RECORD_ID));

ALTER TABLE TB_STMENUGRANTLINK ADD (
  CONSTRAINT TB_STMENUGRANTLINK_FK01 FOREIGN KEY (RECORD_CENTER_ID, MENU_ID) 
 REFERENCES TB_STMENU (RECORD_CENTER_ID, MENU_ID),
  CONSTRAINT TB_STMENUGRANTLINK_FK02 FOREIGN KEY (RECORD_CENTER_ID, MENU_GRANT_GRP_CD) 
 REFERENCES TB_STMENUGRANTGRP (RECORD_CENTER_ID, MENU_GRANT_GRP_CD));


ALTER TABLE TB_ADARCHIVALOBJDISUSE ADD (
  CONSTRAINT TB_ADARCHIVALOBJDISUSE_FK01 FOREIGN KEY (RECORD_CENTER_ID, ADMNATNL_ID) 
  REFERENCES TB_ADARCHIVALOBJ (RECORD_CENTER_ID, ADMNATNL_ID));

ALTER TABLE TB_ADARCHIVALOBJIMG ADD (
  CONSTRAINT TB_ADARCHIVALOBJIMG_FK01 FOREIGN KEY (RECORD_CENTER_ID, ADMNATNL_ID) 
  REFERENCES TB_ADARCHIVALOBJ (RECORD_CENTER_ID, ADMNATNL_ID));

ALTER TABLE TB_ADARCHIVAL_DST ADD (
  CONSTRAINT TB_ADARCHIVAL_DST_FK01 FOREIGN KEY (RECORD_CENTER_ID, ADMNATNL_ID) 
  REFERENCES TB_ADARCHIVALOBJ (RECORD_CENTER_ID, ADMNATNL_ID));

ALTER TABLE TB_GVPUBL_FILE ADD (
  CONSTRAINT TB_GVPUBL_FILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, PUBL_REG_ID, PUBL_REG_SEQ) 
  REFERENCES TB_GVPUBL (RECORD_CENTER_ID, PUBL_REG_ID, PUBL_REG_SEQ));


ALTER TABLE TB_SROPTIDISK_BOOKSF ADD (
  CONSTRAINT TB_SROPTIDISK_BOOKSF_FK01 FOREIGN KEY (RECORD_CENTER_ID, OPTIDISK_STAKRM_ID) 
  REFERENCES TB_SROPTIDISK_STAKRM (RECORD_CENTER_ID, OPTIDISK_STAKRM_ID));

ALTER TABLE TB_SROPTIDISK_CNTCHKDETL ADD (
  CONSTRAINT TB_SROPTIDISK_CNTCHKDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, MEDIA_DIV, CNTCHK_ID)
  REFERENCES TB_SROPTIDISK_CNTCHK (RECORD_CENTER_ID, MEDIA_DIV, CNTCHK_ID)
);

ALTER TABLE TB_SROPTIDISK_MST ADD (
  CONSTRAINT TB_SROPTIDISK_MST_FK01 FOREIGN KEY (RECORD_CENTER_ID, OPTIDISK_STAKRM_ID, OPTIDISK_BOOKSF_ID) 
  REFERENCES TB_SROPTIDISK_BOOKSF (RECORD_CENTER_ID, OPTIDISK_STAKRM_ID, OPTIDISK_BOOKSF_ID));

ALTER TABLE TB_RFTABPUB ADD (
  CONSTRAINT TB_RFTABPUB_FK02 FOREIGN KEY (RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID) 
  REFERENCES TB_SRBOOKSF (RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID),
  CONSTRAINT TB_RFTABPUB_FK03 FOREIGN KEY (RECORD_CENTER_ID, PIC_SNO) 
  REFERENCES TB_SRMFPIC (RECORD_CENTER_ID, PIC_SNO),
  CONSTRAINT TB_RFTABPUB_FK04 FOREIGN KEY (RECORD_CENTER_ID, PRESV_BOX_ID) 
  REFERENCES TB_SRPRESVBOX (RECORD_CENTER_ID, PRESV_BOX_ID));

ALTER TABLE TB_RFTABPUBHIST ADD (
  CONSTRAINT TB_RFTABPUBHIST_FK01 FOREIGN KEY (TAG_ID) 
  REFERENCES TB_RFTABPUB (TAG_ID),
  CONSTRAINT TB_RFTABPUBHIST_FK02 FOREIGN KEY (RECORD_CENTER_ID, TAGPRINT_ID) 
  REFERENCES TB_RFTABPRINT (RECORD_CENTER_ID, TAGPRINT_ID));

ALTER TABLE TB_RCFOLDERCHNGHIST ADD (
  CONSTRAINT TB_RCFOLDERCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCFOLDERCREAT ADD (
  CONSTRAINT TB_RCFOLDERCREAT_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCFOLDERKEYWD ADD (
  CONSTRAINT TB_RCFOLDERKEYWD_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCFOLDERPJTCLSS ADD (
  CONSTRAINT TB_RCFOLDERPJTCLSS_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCFOLDERREL ADD (
  CONSTRAINT TB_RCFOLDERREL_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCFOLDERTAKETAKOVR ADD (
  CONSTRAINT TB_RCFOLDERTAKETAKOVR_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCDISUSEOPINHIST ADD (
  CONSTRAINT TB_RCDISUSEOPINHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCFOLDERNEOFILE ADD (
  CONSTRAINT TB_RCFOLDERNEOFILE_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCRECORD ADD (
  CONSTRAINT TB_RCRECORD_FK01 FOREIGN KEY (RECORD_CENTER_ID, FOLDER_ID) 
  REFERENCES TB_RCFOLDER (RECORD_CENTER_ID, FOLDER_ID));

ALTER TABLE TB_RCRECORDCHNGHIST ADD (
  CONSTRAINT TB_RCRECORDCHNGHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCRECORDCREAT ADD (
  CONSTRAINT TB_RCRECORDCREAT_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCRECORDINFOSRC ADD (
  CONSTRAINT TB_RCRECORDINFOSRC_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCRECORDKEYWD ADD (
  CONSTRAINT TB_RCRECORDKEYWD_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCRECORDREL ADD (
  CONSTRAINT TB_RCRECORDREL_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCRECORDTITLEHIST ADD (
  CONSTRAINT TB_RCRECORDTITLEHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCOPENHIST ADD (
  CONSTRAINT TB_RCOPENHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));

ALTER TABLE TB_RCRANGERESORTHIST ADD (
  CONSTRAINT TB_RCRANGERESORTHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_ID) 
  REFERENCES TB_RCRECORD (RECORD_CENTER_ID, RECORD_ID));


ALTER TABLE TB_RDRANGERESORTOPIN ADD (
  CONSTRAINT TB_RDRANGERESORTOPIN_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));
    
ALTER TABLE TB_RDRANGERESORTHIST ADD (
  CONSTRAINT TB_RDRANGERESORTHIST_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_RDRECORD (RECORD_ID));
    
ALTER TABLE TB_DFDISUSEOPINHIST ADD (
  CONSTRAINT TB_DFDISUSEOPINHIST_FK01 FOREIGN KEY (FOLDER_ID) 
    REFERENCES TB_RDFOLDER (FOLDER_ID));

ALTER TABLE TB_NKDISUSEOPINHIST ADD (
  CONSTRAINT TB_NKDISUSEOPINHIST_FK01 FOREIGN KEY (FOLDER_ID)
  REFERENCES TB_NKFOLDER (FOLDER_ID));

ALTER TABLE TB_NKFOLDERCREAT ADD (
  CONSTRAINT TB_NKFOLDERCREAT_FK01 FOREIGN KEY (FOLDER_ID)
  REFERENCES TB_NKFOLDER (FOLDER_ID));

ALTER TABLE TB_NKFOLDERKEYWD ADD (
  CONSTRAINT TB_NKFOLDERKEYWD_FK01 FOREIGN KEY (FOLDER_ID)
  REFERENCES TB_NKFOLDER (FOLDER_ID));

ALTER TABLE TB_NKFOLDERREADDETL ADD (
  CONSTRAINT TB_NKFOLDERREADDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, READ_REQNO)
  REFERENCES TB_NKREADREQ (RECORD_CENTER_ID,READ_REQNO));

ALTER TABLE TB_NKRECORDCREAT ADD (
  CONSTRAINT TB_NKRECORDCREAT_FK01 FOREIGN KEY (RECORD_ID) 
    REFERENCES TB_NKRECORD (RECORD_ID));

ALTER TABLE TB_NKRECORDKEYWD ADD (
  CONSTRAINT TB_NKRECORDKEYWD_FK01 FOREIGN KEY (RECORD_ID)
  REFERENCES TB_NKRECORD (RECORD_ID));


ALTER TABLE TB_NKRECORDREADDETL ADD (
  CONSTRAINT TB_NKRECORDREADDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, READ_REQNO)
  REFERENCES TB_NKREADREQ (RECORD_CENTER_ID,READ_REQNO));

ALTER TABLE TB_NKTRANSFHIST ADD (
  CONSTRAINT TB_NKTRANSFHIST_FK01 FOREIGN KEY (FOLDER_ID)
  REFERENCES TB_NKFOLDER (FOLDER_ID),
  CONSTRAINT TB_NKTRANSFHIST_FK02
  FOREIGN KEY (RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO)
  REFERENCES TB_NKTRANSFWORK (RECORD_CENTER_ID,TRANSF_YYYY,TRANSF_GRP_SNO));

ALTER TABLE TB_TKRECORDOPENHIST ADD
(
	CONSTRAINT TB_TKRECORDOPENHIST_FK01 FOREIGN KEY (RECORD_CENTER_ID, RECORD_TAKE_SEQ)
	REFERENCES TB_TKRECORD (RECORD_CENTER_ID, RECORD_TAKE_SEQ)
);

ALTER TABLE TB_RDRECORDOPENHIST ADD
(
	CONSTRAINT TB_RDRECORDOPENHIST_FK01 FOREIGN KEY (RECORD_ID)
	REFERENCES TB_RDRECORD (RECORD_ID)
);
  
ALTER TABLE TB_RDRECORDDAMGLOSS ADD
(
	CONSTRAINT TB_RDRECORDDAMGLOSS_FK01 FOREIGN KEY (RECORD_ID)
	REFERENCES TB_RDRECORD (RECORD_ID)
);

ALTER TABLE TB_DFTRANSFTAKERESULTDETL ADD
(
	CONSTRAINT TB_DFTRANSFTAKERESULTDETL_FK01 FOREIGN KEY (RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO, FOLDER_ID)
	REFERENCES TB_DFTRANSFTAKERESULT (RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO, FOLDER_ID)
);
  
ALTER TABLE TB_RFTRANHIST ADD
(
	CONSTRAINT TB_RFTRANHIST_FK01 FOREIGN KEY (TAG_ID)
	REFERENCES TB_RFTABPUB (TAG_ID)
);

spool off

