set echo on
spool /data/oracle/admin/RMSORA9I/logs/03_CreateIndex.log

CREATE INDEX TB_CRDISTR_IX01 ON TB_CRDISTR
(RECORD_CENTER_ID, CR_REPORT_ORG_CD, CR_REPORT_YYYY)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRFOLDER_IX01 ON TB_CRFOLDER
(CR_REPORT_YYYY, RECORD_CENTER_ID, CR_REPORT_ORG_CD, CREAT_SYS_CD)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRFOLDER_IX03 ON TB_CRFOLDER
(RECORD_CENTER_ID, CLSS_DIV_CD, CLSS_ID, FOLDER_BISPJT_DIV_CD)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRFOLDER_IX04 ON TB_CRFOLDER
(RECORD_CENTER_ID, CR_REPORT_YYYY, CR_REPORT_ORG_CD, CREAT_SYS_CD, CR_REPORT_SNO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRFOLDER_IX02 ON TB_CRFOLDER
(RECORD_CENTER_ID, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRFOLDER_IX05 ON TB_CRFOLDER
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRFOLDER_IX06 ON TB_CRFOLDER
(RECORD_CENTER_ID, CR_REPORT_ORG_CD, CREAT_YYYY, CLSS_ID, FOLDER_REG_SEQ, CREAT_SYS_CD, HO_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_CRFOLDER_UX01 ON TB_CRFOLDER
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRINFRMRECORD_IX01 ON TB_CRINFRMRECORD
(RECORD_CENTER_ID, INFRM_CREAT_SYS_CD, INFRM_ORG_CD, INFRM_CLSS_ID, INFRM_CREAT_YYYY, INFRM_FOLDER_REG_SEQ, INFRM_HO_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRINFRMRECVRESULT_IX01 ON TB_CRINFRMRECVRESULT
(REP_ORG_CD, CR_REPORT_INFRM_YYYY)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRRECORD_IX01 ON TB_CRRECORD
(RECORD_CENTER_ID, FOLDER_RECV_SEQ)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;


CREATE INDEX TB_CRRECORD_IX02 ON TB_CRRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;


CREATE INDEX TB_CRRECORD_IX03 ON TB_CRRECORD
(RECORD_CENTER_ID, CREAT_YYYY, ORG_CD, CREAT_REG_NO, DTCH_REG_NO, CREAT_SYS_CD)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;


CREATE INDEX TB_CRRECORD_IX04 ON TB_CRRECORD
(ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRRECORD_IX05 ON TB_CRRECORD
(CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRRECORD_IX06 ON TB_CRRECORD
(RECORD_CENTER_ID, CREAT_REG_DTIME, CREAT_REG_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRRECORD_IX07 ON TB_CRRECORD
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRSPCLLIST_IX01 ON TB_CRSPCLLIST
(RECORD_CENTER_ID, FOLDER_RECV_SEQ)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_CRSPCLLIST_IX02 ON TB_CRSPCLLIST
(RECORD_CENTER_ID, RECORD_RECV_SEQ)
LOGGING
TABLESPACE TS_CRIDX01
NOPARALLEL;

CREATE INDEX TB_DFDISUSEHIST_IX02 ON TB_DFDISUSEHIST
(RECORD_CENTER_ID, DISUSE_YYYY)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFDISUSEHIST_IX03 ON TB_DFDISUSEHIST
(RECORD_CENTER_ID, ORG_CD, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFDISUSEHIST_IX04 ON TB_DFDISUSEHIST
(RECORD_CENTER_ID, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFORGTAKOVRLIST_IX01 ON TB_DFORGTAKOVRLIST
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFORGTAKOVRORG_IX01 ON TB_DFORGTAKOVRORG
(RECORD_CENTER_ID, ORG_CD)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFRECVTRANSFLIST_IX01 ON TB_DFRECVTRANSFLIST
(RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFRECVTRANSFLIST_IX02 ON TB_DFRECVTRANSFLIST
(RECORD_CENTER_ID, ORG_CD, CLSS_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFRECVTRANSFLIST_IX03 ON TB_DFRECVTRANSFLIST
(RECORD_CENTER_ID, CLSS_DIV_CD, CLSS_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFRECVTRANSFLIST_IX04 ON TB_DFRECVTRANSFLIST
(RECORD_CENTER_ID, TRANSF_YYYY, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFREVALHIST_IX01 ON TB_DFREVALHIST
(RECORD_CENTER_ID, EVAL_DISCU_NO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTRANSFHIST_IX01 ON TB_DFTRANSFHIST
(RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_MGFOLDER_IX01 ON TB_MGFOLDER
(RECORD_CENTER_CD, MIG_FLAG)
LOGGING
TABLESPACE TS_MGIDX01
NOPARALLEL;


CREATE INDEX TB_MGFOLDER_IX02 ON TB_MGFOLDER
(REG_DTIME, MIG_FLAG)
LOGGING
TABLESPACE TS_MGIDX01
NOPARALLEL;

CREATE INDEX TB_MGRECORD_IX01 ON TB_MGRECORD
(RECORD_CENTER_CD, FOLDER_ID)
LOGGING
TABLESPACE TS_MGIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX01 ON TB_RDFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_YYYY_SNO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX02 ON TB_RDFOLDER
(RECORD_CENTER_ID, CLSS_ID, CLSS_DIV_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX03 ON TB_RDFOLDER
(RECORD_CENTER_ID, CUR_KEEP_ORG_CD, CREAT_YYYY)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX04 ON TB_RDFOLDER
(RECORD_CENTER_ID, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX05 ON TB_RDFOLDER
(RECORD_CENTER_ID, PRESV_BOX_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX06 ON TB_RDFOLDER
(CREAT_SYS_FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX07 ON TB_RDFOLDER
(RECORD_CENTER_ID, CREAT_YYYY)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX08 ON TB_RDFOLDER
(RECORD_CENTER_ID, TAKOVR_RECORD_CENTER_ID, ORG_TAKE_YYYY, ORG_TAKE_SNO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX09 ON TB_RDFOLDER
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ, MIG_FLAG)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX10 ON TB_RDFOLDER
(RECORD_CENTER_ID, ORG_CD, CREAT_YYYY, FOLDER_REG_SEQ, CLSS_ID, CREAT_SYS_CD, HO_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX11 ON TB_RDFOLDER
(RECORD_CENTER_ID, MEDIUM, MF_PIC_STATE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX12 ON TB_RDFOLDER
(RECORD_CENTER_ID, TITLE)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX13 ON TB_RDFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_MNG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX14 ON TB_RDFOLDER
(RECORD_CENTER_ID, FOLDER_ID, NEO_JOB_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX15 ON TB_RDFOLDER
(RECORD_CENTER_ID, ORG_CD, CREAT_SYS_CD, OPER_READ_RANGE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDER_IX16 ON TB_RDFOLDER
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX TB_RDFOLDER_UX01 ON TB_RDFOLDER
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDERACCS_IX01 ON TB_RDFOLDERACCS
(ACCS_USER_ID, ACCS_TYPE_CD, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDERACCS_IX02 ON TB_RDFOLDERACCS
(ACCS_DEPT_CD, ACCS_TYPE_CD, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDERREADDETL_IX01 ON TB_RDFOLDERREADDETL
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDERREADDETL_IX02 ON TB_RDFOLDERREADDETL
(KEEP_RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDFOLDERREADRANG_IX01 ON TB_RDFOLDERREADRANG
(RECORD_CENTER_ID, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORT_IX01 ON TB_RDOPENRESORT
(RECORD_CENTER_ID, RESORT_YYYY, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDOPENRESORT_IX02 ON TB_RDOPENRESORT
(RECORD_CENTER_ID, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX01 ON TB_RDRECORD
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX02 ON TB_RDRECORD
(RECORD_CENTER_ID, CREAT_YYYY, ORG_CD, CREAT_SYS_CD, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX03 ON TB_RDRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_SYS_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX04 ON TB_RDRECORD
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_YYYY_SNO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX05 ON TB_RDRECORD
(RECORD_CENTER_ID, CREAT_SYS_RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX06 ON TB_RDRECORD
(RECORD_CENTER_ID, RECORD_TAKE_SEQ, MIG_FLAG)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX07 ON TB_RDRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX08 ON TB_RDRECORD
(RECORD_CENTER_ID, TITLE)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX09 ON TB_RDRECORD
(RECORD_CENTER_ID, CREAT_REG_DTIME, CREAT_REG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX10 ON TB_RDRECORD
(RECORD_CENTER_ID, FOLDER_ID, SCAN_FIN_FLAG)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX11 ON TB_RDRECORD
(RECORD_CENTER_ID, PDF_JOB_ID, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX12 ON TB_RDRECORD
(RECORD_CENTER_ID, NEO_JOB_ID, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX13 ON TB_RDRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_SYS_CD, OPER_READ_RANGE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX14 ON TB_RDRECORD
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX15 ON TB_RDRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_REG_DTIME)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX16 ON TB_RDRECORD
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX17 ON TB_RDRECORD
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORD_IX18 ON TB_RDRECORD 
(RECORD_CENTER_ID, FOLDER_ID, OPEN_RESORT_PROG_STATE)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL
PCTFREE 10;

CREATE INDEX TB_RDRECORD_IX19 ON TB_RDRECORD 
(RECORD_CENTER_ID, FOLDER_ID, READ_RANGERESORT_PROG_STATE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL
PCTFREE 10;

CREATE INDEX TB_RDRECORD_IX20 ON TB_RDRECORD 
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CREAT_YYYY, DOC_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORDACCS_IX01 ON TB_RDRECORDACCS
(ACCS_USER_ID, ACCS_TYPE_CD, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDRECORDACCS_IX02 ON TB_RDRECORDACCS
(ACCS_DEPT_CD, ACCS_TYPE_CD, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORDREADDETL_IX01 ON TB_RDRECORDREADDETL
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORDREADDETL_IX02 ON TB_RDRECORDREADDETL
(KEEP_RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORDREADRANG_IX01 ON TB_RDRECORDREADRANG
(RECORD_CENTER_ID, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORDREL_IX01 ON TB_RDRECORDREL
(REL_TRGT_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDTAKETAKOVRCLSS_IX01 ON TB_RDTAKETAKOVRCLSS
(TAKE_TAKOVR_MNG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDTAKETAKOVRLIST_IX01 ON TB_RDTAKETAKOVRLIST
(TAKE_TAKOVR_MNG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDTAKETAKOVRPLAN_IX01 ON TB_RDTAKETAKOVRPLAN
(TAKE_TAKOVR_MNG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDTAKETAKOVRPLAN_IX02 ON TB_RDTAKETAKOVRPLAN
(RECORD_CENTER_ID, TAKE_TAKOVR_DIV_CD, TAKE_TAKOVR_REP_CD, TAKE_TAKOVR_YYYY, TAKE_TAKOVR_SNO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_SRBOOKSFARNG_IX01 ON TB_SRBOOKSFARNG
(RECORD_CENTER_ID, PLAN_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRBOOKSFARNGDETL_IX01 ON TB_SRBOOKSFARNGDETL
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRBOOKSFARNGDETL_IX02 ON TB_SRBOOKSFARNGDETL
(RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRCNTCHK_IX01 ON TB_SRCNTCHK
(RECORD_CENTER_ID, PLAN_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRCNTCHKDETL_IX01 ON TB_SRCNTCHKDETL
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRCNTCHKDETL_IX02 ON TB_SRCNTCHKDETL
(RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRCNTCHKDETL_IX03 ON TB_SRCNTCHKDETL
(RECORD_CENTER_ID, CHECK_YMD, FOLDER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_SRIN_UX01 ON TB_SRIN
(RECORD_CENTER_ID, IN_YYYY, IN_SNO)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRIN_IX02 ON TB_SRIN
(RECORD_CENTER_ID, IN_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRIN_IX03 ON TB_SRIN
(RECORD_CENTER_ID, IN_USER_NM)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRINOUTFOLDER_IX02 ON TB_SRINOUTFOLDER
(RECORD_CENTER_ID, IN_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRINOUTFOLDER_IX01 ON TB_SRINOUTFOLDER
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRMFCOPY_IX01 ON TB_SRMFCOPY
(RECORD_CENTER_ID, COPY_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRMFPIC_IX01 ON TB_SRMFPIC
(RECORD_CENTER_ID, MF_STAKRM_ID, MF_BOOKSF_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRMFPIC_IX02 ON TB_SRMFPIC
(RECORD_CENTER_ID, PIC_EXPT_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRMFPIC_IX03 ON TB_SRMFPIC
(RECORD_CENTER_ID, CREAT_ORG_CD, PIC_EXPT_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRMFPIC_IX04 ON TB_SRMFPIC
(RECORD_CENTER_ID, PIC_USER_NM, CREAT_ORG_CD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRMFPICDETL_IX01 ON TB_SRMFPICDETL
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SROPTIDISK_IX03 ON TB_SROPTIDISK
(RECORD_CENTER_ID, STORE_PLAN_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_SROPTIDISK_UX01 ON TB_SROPTIDISK
(ORG_CD, PRESV_TERM_DIV_SYM, OPEN_DIV_SYM, ACCUM_SNO, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SROPTIDISK_IX02 ON TB_SROPTIDISK
(WORK_USER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SROPTIDISKDETL_IX01 ON TB_SROPTIDISKDETL
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_SROUT_UX01 ON TB_SROUT
(RECORD_CENTER_ID, OUT_YYYY, OUT_SNO)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SROUT_IX02 ON TB_SROUT
(RECORD_CENTER_ID, OUT_YMD, OUT_TYPE_CD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SROUT_IX03 ON TB_SROUT
(RECORD_CENTER_ID, OUT_USER_NM)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SROUT_IX04 ON TB_SROUT
(RECORD_CENTER_ID, RETRN_EXPT_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SRPRESVBOX_IX01 ON TB_SRPRESVBOX
(RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_STDEPT_IX01 ON TB_STDEPT
(RECORD_CENTER_ID, ORG_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFOLDERNEOFILE_IX01 ON TB_STFOLDERNEOFILE
(RECORD_CENTER_ID, MEDIUM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STFOLDERNEOFILE_IX02 ON TB_STFOLDERNEOFILE
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_STFOLDERNEOFILE_UX01 ON TB_STFOLDERNEOFILE
(RECORD_CENTER_ID, FOLDER_ID, CHNG_SNO)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL
;

CREATE INDEX TB_STINFOFILE_IX01 ON TB_STINFOFILE
(RECORD_CENTER_ID, MEDIUM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STMEDIUM_IX01 ON TB_STMEDIUM
(RECORD_CENTER_ID, VOLM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STMENU_IX01 ON TB_STMENU
(UPPER_MENU_ID, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STMENU_IX02 ON TB_STMENU
(MENU_LINK_SNO)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STNOTI_IX01 ON TB_STNOTI
(RECORD_CENTER_ID, USER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STORG_IX02 ON TB_STORG
(RECORD_CENTER_ID, HUPPER_ORG_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STORG_IX01 ON TB_STORG
(LINK_TRGT_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_STORIGNFILE_UX01 ON TB_STORIGNFILE
(RECORD_CENTER_ID, ORIGN_ID, DOC_TYPE_CD, DOC_TYPE_SNO)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STORIGNFILE_IX01 ON TB_STORIGNFILE
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STORIGNFILE_IX02 ON TB_STORIGNFILE
(RECORD_CENTER_ID, MEDIUM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE  INDEX TB_STORIGNFILEHIST_IX01 ON TB_STORIGNFILEHIST
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE  INDEX TB_STORIGNFILEHIST_IX02 ON TB_STORIGNFILEHIST
(RECORD_CENTER_ID, MEDIUM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STORIGNNEOFILE_IX01 ON TB_STORIGNNEOFILE
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STORIGNNEOFILE_IX02 ON TB_STORIGNNEOFILE
(RECORD_CENTER_ID, MEDIUM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STORIGNNEOFILE_IX03 ON TB_STORIGNNEOFILE
(RECORD_CENTER_ID, ORIGN_ID, CHNG_SNO)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;



CREATE INDEX TB_STORIGNPAGE_IX01 ON TB_STORIGNPAGE
(ORIGN_FILE_ID, ORIGN_PAGE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STORIGNPAGE_DELETE_IX01 ON TB_STORIGNPAGE_DELETE
(ORIGN_FILE_ID, ORIGN_PAGE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX STORIGNPAGEHIST_IX01 ON TB_STORIGNPAGEHIST
(ORIGN_FILE_ID, ORIGN_PAGE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE UNIQUE INDEX TB_STORIGNPDFA1FILE_UX01 ON TB_STORIGNPDFA1FILE
(RECORD_CENTER_ID, ORIGN_ID, DOC_TYPE_CD, DOC_TYPE_SNO)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STORIGNPDFA1FILE_IX02 ON TB_STORIGNPDFA1FILE
(RECORD_CENTER_ID, MEDIUM_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;



CREATE INDEX TB_STORIGNPDFA1PAGE_IX01 ON TB_STORIGNPDFA1PAGE
(PDF_A1_FILE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STQNA_IX01 ON TB_STQNA
(REF_BOARD_SNO)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STQNA_IX02 ON TB_STQNA
(USER_ID, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STQNA_IX03 ON TB_STQNA
(RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;




CREATE INDEX TB_STRECORDCENTER_IX01 ON TB_STRECORDCENTER
(RECORD_CENTER_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STRECORDORIGN_IX01 ON TB_STRECORDORIGN
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STRECORDORIGN_IX02 ON TB_STRECORDORIGN
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE  INDEX TB_STRECORDORIGNHIST_IX01 ON TB_STRECORDORIGNHIST
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE  INDEX TB_STRECORDORIGNHIST_IX02 ON TB_STRECORDORIGNHIST
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STREFDATA_IX01 ON TB_STREFDATA
(USER_ID, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STREFDATA_IX02 ON TB_STREFDATA
(RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STSTAKRMINFO_IX01 ON TB_STSTAKRMINFO
(INFO_FILE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STUSER_IX01 ON TB_STUSER
(RECORD_CENTER_ID, DEPT_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STUSER_IX02 ON TB_STUSER
(LOGIN_USER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STUSER_IX03 ON TB_STUSER
(DEPT_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STUSER_IX04 ON TB_STUSER
(SSO_FLAG, SSO_KEY)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STUSERGRP_IX01 ON TB_STUSERGRP
(RECORD_CENTER_ID, GRANT_GRP_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STUSERGRPMENU_IX01 ON TB_STUSERGRPMENU
(RECORD_CENTER_ID, MENU_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STUSERMENUGRANT_IX01 ON TB_STUSERMENUGRANT
(RECORD_CENTER_ID, MENU_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_QUEUE_IX01 ON TB_STFORMAT_QUEUE
(JOB_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_QUEUE_IX02 ON TB_STFORMAT_QUEUE
(JOB_GROUP_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_QUEUE_IX03 ON TB_STFORMAT_QUEUE
(RECORD_CENTER_ID, FOLDER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_HIST_IX01 ON TB_STFORMAT_HIST
(JOB_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_HIST_IX02 ON TB_STFORMAT_HIST
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_FILE_IX01 ON TB_STFORMAT_FILE
(JOB_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STFORMAT_FILE_IX02 ON TB_STFORMAT_FILE
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_TKATTACHFILE_IDX01 ON TB_TKATTACHFILE
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKATTACHFILE_IX02 ON TB_TKATTACHFILE
(RECORD_CENTER_ID, CREAT_YYYY, CREAT_REG_NO, ATTACH_FILE_SEQ, DOC_TYPE_CD, RECORD_TAKE_SEQ)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDER_IX01 ON TB_TKFOLDER
(RECORD_CENTER_ID, CREAT_YYYY, TAKE_ORG_CD)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDER_IX02 ON TB_TKFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_ORG_CD, TAKE_SNO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDER_IX03 ON TB_TKFOLDER
(RECORD_CENTER_ID, CREAT_SYS_CD, TAKE_ORG_CD, CLSS_ID, CREAT_YYYY, 
FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDER_IX04 ON TB_TKFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_ORG_CD, CREAT_SYS_CD, TAKE_SNO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDER_IX05 ON TB_TKFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_MNG_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_RDFOLDERREADRANG_IX02 ON TB_TKFOLDERREADRANG
(HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_TKFOLDERREG_IX01 ON TB_TKFOLDERREG
(RECORD_CENTER_ID, ORG_CD, CLSS_DIV_CD, CLSS_ID)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDERREG_IX02 ON TB_TKFOLDERREG
(CREAT_YYYY, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDERREG_IX03 ON TB_TKFOLDERREG
(CLSS_DIV_CD, CLSS_ID)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_RDOPENREVW_IX01 ON TB_RDOPENREVW
(RECORD_CENTER_ID, RECORD_ID, DISCU_SEQ)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDOPENRESORT_IX03 ON TB_TKOPENRESORT
(RESORT_YYYY, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDOPENRESORT_IX04 ON TB_TKOPENRESORT
(HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_TKORGTAKEPLAN_IX01 ON TB_TKORGTAKEPLAN
(RECORD_CENTER_ID, TAKE_YMD)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;



CREATE INDEX TB_TKORGTAKESCHED_IX01 ON TB_TKORGTAKESCHED
(ERECORD_TAKE_START_PLAN_YMD, ERECORD_TAKE_CLOSE_PLAN_YMD)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKRECORD_IX01 ON TB_TKRECORD
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKRECORD_IX02 ON TB_TKRECORD
(ORG_CD, CREAT_SYS_CD, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKRECORD_IX03 ON TB_TKRECORD
(ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKRECORD_IX04 ON TB_TKRECORD
(CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKRECORD_IX05 ON TB_TKRECORD
(RECORD_CENTER_ID, CREAT_REG_DTIME, CREAT_REG_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKRECORD_IX06 ON TB_TKRECORD
(RECORD_CENTER_ID, RECORD_SNO, CREAT_REG_DTIME, CREAT_REG_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_RDRECORDREADRANG_IX02 ON TB_TKRECORDREADRANG
(HANDL_ORG_CD)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKRECORDREG_IX01 ON TB_TKRECORDREG
(RECORD_CENTER_ID, FOLDER_REG_TAKE_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKRECORDREG_IX02 ON TB_TKRECORDREG
(CREAT_YYYY, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKRECORDREG_IX03 ON TB_TKRECORDREG
(ORG_CD, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKSPLLIST_IX03 ON TB_TKSPCLLIST
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ, SEQ)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKSPCLLIST_IX01 ON TB_TKSPCLLIST
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKSPCLLIST_IX02 ON TB_TKSPCLLIST
(RECORD_CENTER_ID, RECORD_TAKE_SEQ)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_ZZBISCLSS_IX01 ON TB_ZZBISCLSS
(UPPER_BIS_CLSS_ID)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZBISCLSS_IX02 ON TB_ZZBISCLSS
(TRANS_UNIT_CD)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZBISCLSS_IX03 ON TB_ZZBISCLSS
(START_DTIME)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZBISCLSSHIST_IX01 ON TB_ZZBISCLSSHIST
(BIS_CLSS_ID, WORK_DTIME)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE UNIQUE INDEX TB_ZZBISCLSSRELLAW_UX01 ON TB_ZZBISCLSSRELLAW
(BIS_CLSS_ID, LAW_ID, ARTIC_NO, LOWER_ARTIC_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZBISORG_IX01 ON TB_ZZBISORG
(ORG_CD)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZBISORG_IX02 ON TB_ZZBISORG
(BIS_CLSS_ID)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZORGCOMSTND_IX01 ON TB_ZZORGCOMSTND
(RECORD_CENTER_ID, STND_MNG_TYPE_CD, VER)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZORGUNIT_IX01 ON TB_ZZORGUNIT
(RECORD_CENTER_ID, UNIT_CD)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZPJTCLSS_IX01 ON TB_ZZPJTCLSS
(UPPER_PJT_CLSS_ID)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZPJTMAPPNG_IX01 ON TB_ZZPJTMAPPNG
(BIS_CLSS_ID)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZPRESVTERMRULE_IX01 ON TB_ZZPRESVTERMRULE
(RECORD_CENTER_ID, STND_MNG_TYPE_CD, VER)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZSTNDMNG_IX01 ON TB_ZZSTNDMNG
(RECORD_CENTER_ID, RECV_DTIME)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZTRACE_IX01 ON TB_ZZTRACE
(USER_ID, TRGT_DIV_CD, TRGT_ID)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZTRACE_IX02 ON TB_ZZTRACE
(RECORD_CENTER_ID, WORK_DTIME)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;



CREATE INDEX TB_ZZUNITTEMP_IDX01 ON TB_ZZUNITTEMP
(RECORD_CENTER_ID, UNIT_CD)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZUNITTEMP_IDX02 ON TB_ZZUNITTEMP
(RECORD_CENTER_ID, ORG_CD, UNIT_CD)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_ZZREQLISTTEMP_IDX01 ON TB_ZZREQLISTTEMP
(RECORD_CENTER_ID, REMK)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;


CREATE INDEX TB_SRSTAKRM_IDX01 ON TB_SRSTAKRM
(RECORD_CENTER_ID, STAKRM_NM)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SRBOOKSF_IX01 ON TB_SRBOOKSF
(RECORD_CENTER_ID, STAKRM_ID, BOOKSF_NM)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_ZZUNITDELREQ_IX01 ON TB_ZZUNITDELREQ
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZUNITREQ_IX01 ON TB_ZZUNITREQ
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZUNITNEWREQ_IX01 ON TB_ZZUNITNEWREQ
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZUNITMOVEREQ_IX01 ON TB_ZZUNITMOVEREQ
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZUNITCHNGREQ_IX01 ON TB_ZZUNITCHNGREQ
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;

CREATE INDEX TB_ZZORGUNITWORKHIST_IX01 ON TB_ZZORGUNITWORKHIST
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_ZZIDX01
NOPARALLEL;





CREATE INDEX TB_DFDISUSEDISCU_IX01 ON TB_DFDISUSEDISCUDOC
(DISCU_YYYY)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFDISUSEOPIN_IX01 ON TB_DFDISUSEOPIN
(DISCU_SEQ)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;


CREATE INDEX TB_DFDISUSEOPIN_IX02 ON TB_DFDISUSEOPIN
(ORG_CD)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;


CREATE INDEX TB_DFDISUSEOPIN_IX03 ON TB_DFDISUSEOPIN
(DISCU_PROG_STATE_CD)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;


CREATE INDEX TB_DFDISUSEOPIN_IX04 ON TB_DFDISUSEOPIN
(EVAL_DISUE_NO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;


CREATE INDEX TB_DFDISUSEOPIN_IX05 ON TB_DFDISUSEOPIN
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFDISUSEOPIN_IX06 ON TB_DFDISUSEOPIN
(RECORD_CENTER_ID, DISCU_YYYY, FOLDER_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;


CREATE INDEX TB_DFDISUSEOPINHIST_IX01 ON TB_DFDISUSEOPINHIST
(DISCU_YYYY)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFDISUSEOPINHIST_IX02 ON TB_DFDISUSEOPINHIST
(RECORD_CENTER_ID, FOLDER_ID, CHNG_HIST_NO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX01 ON TB_RDOPENRESORTOPIN
(RESORT_YYYY)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX02 ON TB_RDOPENRESORTOPIN
(RECORD_CENTER_ID, RESORT_CASE, RESORT_CASE_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX03 ON TB_RDOPENRESORTOPIN
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX04 ON TB_RDOPENRESORTOPIN
(RESORT_PROG_STATE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX05 ON TB_RDOPENRESORTOPIN
(RECORD_CENTER_ID, HANDL_ORG_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX06 ON TB_RDOPENRESORTOPIN
(RECORD_CENTER_ID, RECORD_ID, RESORT_SEQ, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDOPENRESORTOPIN_IX07 ON TB_RDOPENRESORTOPIN 
(RECORD_CENTER_ID, RESORT_YYYY, RESORT_PROG_STATE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL
PCTFREE 10;

CREATE INDEX TB_RDOPENHIST_IX01 ON TB_RDOPENHIST
(RECORD_CENTER_ID, RECORD_ID, CHNG_HIST_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRANGERESORTHIST_IX01 ON TB_RDRANGERESORTHIST
(RESORT_YYYY)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRANGERESORTHIST_IX02 ON TB_RDRANGERESORTHIST
(RECORD_CENTER_ID, RECORD_ID, RESORT_CHNG_HIST_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRANGERESORTOPIN_IX01 ON TB_RDRANGERESORTOPIN
(RESORT_CASE, RESORT_CASE_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRANGERESORTOPIN_IX02 ON TB_RDRANGERESORTOPIN
(RESORT_YYYY)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRANGERESORTOPIN_IX03 ON TB_RDRANGERESORTOPIN
(RESORT_PROG_STATE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;

CREATE INDEX TB_RDRANGERESORTOPIN_IX04 ON TB_RDRANGERESORTOPIN
(RECORD_CENTER_ID, RECORD_ID, RESORT_SEQ)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_STSCHEDULE_IX01 ON TB_STSCHEDULE
(JOB_TYPE)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

-- TB_TKFOLDERTAKEHIST 테이블의 pk와 동일하여 제외
--CREATE INDEX TB_TKFOLDERTAKEHIST_IX01 ON TB_TKFOLDERTAKEHIST
--(RECORD_CENTER_ID, FOLDER_TAKE_SEQ, HIST_SNO)
--LOGGING
--TABLESPACE TS_TKIDX01
--NOPARALLEL;

CREATE INDEX TB_TKFOLDERTAKEHIST_IX02 ON TB_TKFOLDERTAKEHIST
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;


CREATE INDEX TB_TKFOLDERTAKEHIST_IX03 ON TB_TKFOLDERTAKEHIST
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_ORG_CD, TAKE_SNO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_STWORKHIST_IX01 ON TB_STWORKHIST
(RECORD_CENTER_ID, FOLDER_ID, RECORD_ID, ORIGN_FILE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;



CREATE INDEX TB_ADARCHIVALOBJ_IX01 ON TB_ADARCHIVALOBJ
(CLSS)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX02 ON TB_ADARCHIVALOBJ
(SHAPE)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX03 ON TB_ADARCHIVALOBJ
(MATERIAL)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX04 ON TB_ADARCHIVALOBJ
(CREAT_YYYY)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX05 ON TB_ADARCHIVALOBJ
(ADMNATNLHIST_NM)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX06 ON TB_ADARCHIVALOBJ
(ADM_PROG_STATE)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX07 ON TB_ADARCHIVALOBJ
(TRANSF_HANDL_STATE)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;


CREATE INDEX TB_ADARCHIVALOBJ_IX08 ON TB_ADARCHIVALOBJ
(DST_FLAG)
LOGGING
TABLESPACE TS_ADIDX01
NOPARALLEL;

CREATE INDEX TB_GVPUBL_IX01 ON TB_GVPUBL
(CREAT_ORG_NM)
LOGGING
TABLESPACE TS_GVIDX01
NOPARALLEL;


CREATE INDEX TB_GVPUBL_IX02 ON TB_GVPUBL
(PUBL_YMD)
LOGGING
TABLESPACE TS_GVIDX01
NOPARALLEL;


CREATE INDEX TB_GVPUBL_IX03 ON TB_GVPUBL
(TITLE)
LOGGING
TABLESPACE TS_GVIDX01
NOPARALLEL;


CREATE INDEX TB_GVPUBL_IX04 ON TB_GVPUBL
(CREAT_YYYY)
LOGGING
TABLESPACE TS_GVIDX01
NOPARALLEL;



CREATE INDEX TB_SROPTIDISK_CNTCHK_IX01 ON TB_SROPTIDISK_CNTCHK
(RECORD_CENTER_ID, PLAN_YMD)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE INDEX TB_SROPTIDISK_CNTCHKDETL_IX01 ON TB_SROPTIDISK_CNTCHKDETL
(RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SROPTIDISK_CNTCHKDETL_IX02 ON TB_SROPTIDISK_CNTCHKDETL
(OPTIDISK_BOOKSF_ID, OPTIDISK_STAKRM_ID, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SROPTIDISK_CNTCHKDETL_IX03 ON TB_SROPTIDISK_CNTCHKDETL
(CHECK_YMD, RECORD_CENTER_ID)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_SROPTIDISK_MST_UX01 ON TB_SROPTIDISK_MST
(RECORD_CENTER_ID, ORG_CD, SEQ, SPLIT_TOT)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SROPTIDISK_MST_IX01 ON TB_SROPTIDISK_MST
(OPTIDISK_TYPE_CD, ORG_CD, SEQ)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;


CREATE INDEX TB_SROPTIDISK_MST_IX02 ON TB_SROPTIDISK_MST
(OPTIDISK_YYYY)
LOGGING
TABLESPACE TS_SRIDX01
NOPARALLEL;



CREATE INDEX TB_RFTABPUB_IX01 ON TB_RFTABPUB
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL;


CREATE INDEX TB_RFTABPUB_IX02 ON TB_RFTABPUB
(RECORD_CENTER_ID, STAKRM_ID, BOOKSF_ID)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL;


CREATE INDEX TB_RFTABPUB_IX03 ON TB_RFTABPUB
(RECORD_CENTER_ID, PIC_SNO)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL;


CREATE INDEX TB_RFTABPUB_IX04 ON TB_RFTABPUB
(RECORD_CENTER_ID, PRESV_BOX_ID)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL;

CREATE INDEX TB_RFTABPUBHIST_IX01 ON TB_RFTABPUBHIST
(TAG_ID)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL;


CREATE INDEX TB_RFTABPUBHIST_IX02 ON TB_RFTABPUBHIST
(TAGPRINT_ID)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL;


CREATE INDEX TB_RDMULTITAKOVRPLAN_IX01 ON TB_RDMULTITAKOVRPLAN
(RECORD_CENTER_ID, TAKE_TAKOVR_RCV_REP_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDMULTITAKOVRPLAN_IX02 ON TB_RDMULTITAKOVRPLAN
(TAKE_TAKOVR_SND_REP_CD, TAKE_TAKOVR_YYYY, TAKE_TAKOVR_SNO, TAKE_TAKOVR_RCV_REP_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDMULTITAKOVRLIST_IX01 ON TB_RDMULTITAKOVRLIST
(RECORD_CENTER_ID, TAKE_TAKOVR_RCV_REP_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDMULTITAKOVRLIST_IX02 ON TB_RDMULTITAKOVRLIST
(TAKE_TAKOVR_SND_REP_CD, TAKE_TAKOVR_YYYY, TAKE_TAKOVR_SNO, TAKE_TAKOVR_RCV_REP_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDMULTITAKOVRLIST_IX03 ON TB_RDMULTITAKOVRLIST
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDSPCLLIST_IDX01 ON TB_RDSPCLLIST
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDSPCLLIST_IX02 ON TB_RDSPCLLIST
(RECORD_CENTER_ID, RECORD_TAKE_SEQ)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDSPCLLIST_IX03 ON TB_RDSPCLLIST
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ, SEQ)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDATTACHFILE_IDX01 ON TB_RDATTACHFILE
(TAKE_MNG_NO)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDATTACHFILE_IX02 ON TB_RDATTACHFILE
(RECORD_CENTER_ID, CREAT_YYYY, CREAT_REG_NO, ATTACH_FILE_SEQ, DOC_TYPE_CD, RECORD_TAKE_SEQ)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDOPENRESORTAUTO_IDX01 ON TB_RDOPENRESORTAUTO
(RECORD_CENTER_ID, RECORD_ID, RESORT_SEQ, FOLDER_ID)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RDOPENRESORTAUTO_IX02 ON TB_RDOPENRESORTAUTO
(RESORT_PROG_STATE_CD)
LOGGING
TABLESPACE TS_RDIDX01
NOPARALLEL;


CREATE INDEX TB_RCTAKEFOLDERLIST_IX01 ON TB_RCTAKEFOLDERLIST
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_RCTAKEFOLDERLIST_IX02 ON TB_RCTAKEFOLDERLIST (RECORD_CENTER_ID, RD_FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_RCTAKERECORDLIST_IX01 ON TB_RCTAKERECORDLIST
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;


CREATE INDEX TB_RCTAKERECORDLIST_IX02 ON TB_RCTAKERECORDLIST
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_RCFOLDER_IX01 ON TB_RCFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_YYYY_SNO)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_RCFOLDER_UX01 ON TB_RCFOLDER
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_RCFOLDERNEOFILE_IX02 ON TB_RCFOLDERNEOFILE
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_RCRECORD_IX01 ON TB_RCRECORD
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_RCRECORD_IX02 ON TB_RCRECORD
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_RCORIGNPAGEHIST_IX01 ON TB_RCORIGNPAGEHIST
(RECORD_CENTER_ID, RECORD_ID, CHNG_DTIME)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL;

CREATE INDEX TB_DFTAKOVRFOLDERLIST_IDX01 ON TB_DFTAKOVRFOLDERLIST
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTAKEPLAN_IX01 ON TB_DFTAKEPLAN
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_REP_CD, TAKE_SNO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTAKEERROR_IDX01 ON TB_DFTAKEERROR
(TAKE_REP_CD, TAKE_YYYY, TAKE_SNO)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX01 ON TB_NKFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_YYYY_SNO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;


CREATE INDEX TB_NKFOLDER_IX02 ON TB_NKFOLDER
(RECORD_CENTER_ID, CLSS_ID, CLSS_DIV_CD)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;


CREATE INDEX TB_NKFOLDER_IX03 ON TB_NKFOLDER
(RECORD_CENTER_ID, CUR_KEEP_ORG_CD, CREAT_YYYY)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX04 ON TB_NKFOLDER
(RECORD_CENTER_ID, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX05 ON TB_NKFOLDER
(CREAT_SYS_FOLDER_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX06 ON TB_NKFOLDER
(RECORD_CENTER_ID, CREAT_YYYY)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX07 ON TB_NKFOLDER
(RECORD_CENTER_ID, TAKOVR_RECORD_CENTER_ID, ORG_TAKE_YYYY, ORG_TAKE_SNO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX08 ON TB_NKFOLDER
(RECORD_CENTER_ID, FOLDER_TAKE_SEQ, MIG_FLAG)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX09 ON TB_NKFOLDER
(RECORD_CENTER_ID, ORG_CD, CREAT_YYYY, FOLDER_REG_SEQ, CLSS_ID, CREAT_SYS_CD, HO_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX10 ON TB_NKFOLDER
(RECORD_CENTER_ID, MEDIUM, MF_PIC_STATE_CD)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX11 ON TB_NKFOLDER
(RECORD_CENTER_ID, TITLE)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX12 ON TB_NKFOLDER
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_MNG_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX13 ON TB_NKFOLDER
(RECORD_CENTER_ID, ORG_CD, CREAT_SYS_CD, OPER_READ_RANGE_CD)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDER_IX14 ON TB_NKFOLDER
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_NKFOLDER_UX01 ON TB_NKFOLDER
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CLSS_ID, CREAT_YYYY, FOLDER_REG_SEQ, HO_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKDISUSEDISCUDOC_IX01 ON TB_NKDISUSEDISCUDOC
(DISCU_YYYY)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKDISUSEOPINHIST_IX01 ON TB_NKDISUSEOPINHIST
(DISCU_YYYY)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKDISUSEOPINHIST_IX02 ON TB_NKDISUSEOPINHIST
(RECORD_CENTER_ID, FOLDER_ID, CHNG_HIST_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDERREADDETL_IX01 ON TB_NKFOLDERREADDETL
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKFOLDERREADDETL_IX02 ON TB_NKFOLDERREADDETL
(KEEP_RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX01 ON TB_NKRECORD
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX02 ON TB_NKRECORD
(RECORD_CENTER_ID, CREAT_YYYY, ORG_CD, CREAT_SYS_CD, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX03 ON TB_NKRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_SYS_CD)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX04 ON TB_NKRECORD
(RECORD_CENTER_ID, TAKE_YYYY, TAKE_YYYY_SNO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX05 ON TB_NKRECORD
(RECORD_CENTER_ID, CREAT_SYS_RECORD_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX06 ON TB_NKRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX07 ON TB_NKRECORD
(RECORD_CENTER_ID, TITLE)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX08 ON TB_NKRECORD
(RECORD_CENTER_ID, CREAT_REG_DTIME, CREAT_REG_NO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX10 ON TB_NKRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_SYS_CD, OPER_READ_RANGE_CD)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX11 ON TB_NKRECORD
(RECORD_CENTER_ID, ORIGN_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX12 ON TB_NKRECORD
(RECORD_CENTER_ID, ORG_CD, CREAT_REG_DTIME)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORD_IX13 ON TB_NKRECORD
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORDCREAT_IX01 ON TB_NKRECORDCREAT
(AGENT_TYPE_CD, AGENT_NM)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;    

CREATE INDEX TB_NKRECORDREADDETL_IX01 ON TB_NKRECORDREADDETL
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKRECORDREADDETL_IX02 ON TB_NKRECORDREADDETL
(KEEP_RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_NKTRANSFHIST_IX01 ON TB_NKTRANSFHIST
(RECORD_CENTER_ID, TRANSF_YYYY, TRANSF_GRP_SNO)
LOGGING
TABLESPACE TS_NKIDX01
NOPARALLEL;

CREATE INDEX TB_DFTRANSFSTORESLT_IX01 ON TB_DFTRANSFSTORESLT
(RECORD_CENTER_ID, SPLIT_SEQ)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTRANSFSTOREFLD_IX01 ON TB_DFTRANSFSTOREFLD
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTRANSFSTORERCD_IX01 ON TB_DFTRANSFSTORERCD
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTRANSFSTORERCD_IX02 ON TB_DFTRANSFSTORERCD
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_DFTRANSFSTOREERR_IX01 ON TB_DFTRANSFSTOREERR
(RECORD_CENTER_ID, RD_ID)
LOGGING
TABLESPACE TS_DFIDX01
NOPARALLEL;

CREATE INDEX TB_STLOGMONITOR_IX01 ON TB_STLOGMONITOR
(SEND_LIST_FILE_NM, FILE_NM, SVC_DIV, SUCC_FAIL_FLAG)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STLOGMONITOR_IX02 ON TB_STLOGMONITOR
(TRANSF_YYYY, SVC_DIV, SPLIT_SEQ, FOLDER_CLSS_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE UNIQUE INDEX TB_STLOGMONITOR_IX03 ON TB_STLOGMONITOR
(LOG_CREAT_TME, SEND_LIST_FILE_NM, FILE_NM)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STLOGMONITOR_IX04 ON TB_STLOGMONITOR
(LOG_JOB_DIV, SVC_DIV, FILE_NM, SEND_LIST_FILE_NM)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STERRORLOG_IX01 ON TB_STERRORLOG
(FILE_NM, LOG_CREAT_TME)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STORIGNVIRUSCHKHIST_IX01 ON TB_STORIGNVIRUSCHKHIST
(VIRUS_HIST_DIV, FILE_TYPE, FILE_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;


CREATE INDEX TB_STREQTRANS_IX01 ON TB_STREQTRANS
(REQUEST_STATUS, NEO_GUBUN)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STREQTRANS_IX02 ON TB_STREQTRANS
(RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STREQTRANS_IX03 ON TB_STREQTRANS
(RECORD_CENTER_ID, RECORD_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STREQTRANS_IX04 ON TB_STREQTRANS 
(RECORD_CENTER_ID, NEO_GUBUN, REQUEST_STATUS)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_STREQRESULT_IX01 ON TB_STREQRESULT
(JOB_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_STREQFILE_IX01 ON TB_STREQFILE
(JOB_ID)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL;

CREATE INDEX TB_TKVIRUSCHECKHIST_IX01 ON TB_TKVIRUSCHECKHIST
(RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO, DOC_TYPE_CD, DOC_TYPE_SNO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL;

CREATE INDEX TB_TKVIRUSCHECK_IX01 ON TB_TKVIRUSCHECK 
(RECORD_CENTER_ID, CREAT_SYS_CD,ORG_CD,CREAT_YYYY,CREAT_REG_NO,DTCH_REG_NO,DOC_TYPE_CD,DOC_TYPE_SNO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL
;

CREATE INDEX TB_TKRECORDCREAT_IX01 ON TB_TKRECORDCREAT (RECORD_CENTER_ID, RECORD_TAKE_SEQ)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_STWORKHIST_IX02 ON TB_STWORKHIST (FORMAT_DIV_CD)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_TKVIRUSCHECK_IX02 ON TB_TKVIRUSCHECK (VIRUS_CHECK_FLAG, VIRUS_INFECTION_FLAG)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_STORIGNVIRUSCHK_IX01 ON TB_STORIGNVIRUSCHK (FILE_TYPE, VIRUS_CHECK_FLAG, VIRUS_CLEAN_APPLY_FLAG)
LOGGING
TABLESPACE TS_STIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_RFTRANHIST_IX01 ON TB_RFTRANHIST (RECORD_CENTER_ID, FIXREDER_ID)
LOGGING
TABLESPACE TS_RFIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_RFTRANHIST_IX02 ON TB_RFTRANHIST (TAG_ID)
LOGGING
TABLESPACE TS_RFIDX01
PCTFREE    10
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_TKFILECHECK_IX01 ON TB_TKFILECHECK (RECORD_CENTER_ID, CREAT_SYS_CD, ORG_CD, CREAT_YYYY, CREAT_REG_NO, DTCH_REG_NO, DOC_TYPE_CD, DOC_TYPE_SNO)
LOGGING
TABLESPACE TS_TKIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_RCREQTRANS_IX01 ON TB_RCREQTRANS (RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL
PCTFREE 5;


CREATE INDEX TB_RCWORKHIST_IX01 ON TB_RCWORKHIST (RECORD_CENTER_ID, FOLDER_ID)
LOGGING
TABLESPACE TS_RCIDX01
NOPARALLEL
PCTFREE 5;

CREATE INDEX TB_RDRECORDCREAT_IX01 ON TB_RDRECORDCREAT (AGENT_TYPE_CD, AGENT_NM) 
LOGGING 
TABLESPACE TS_RDIDX01 
NOPARALLEL;

CREATE INDEX TB_RCORIGNFILE_IX01 ON TB_RCORIGNFILE(RECORD_CENTER_ID,ORIGN_ID) LOGGING TABLESPACE TS_RCIDX01 NOPARALLEL;
CREATE INDEX TB_RCORIGNPDFA1FILE_IX01 ON TB_RCORIGNPDFA1FILE(RECORD_CENTER_ID, ORIGN_ID, DOC_TYPE_CD, DOC_TYPE_SNO) LOGGING TABLESPACE TS_RCIDX01 NOPARALLEL;

spool off