set echo on
spool /data/oracle/admin/RMSORA9I/logs/05_CreateProcedure.log


CREATE OR REPLACE PROCEDURE SP_RESET_SEQ
IS
  L_VAL NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'SELECT TB_CRFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_CRFOLDER_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_CRFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_CRFOLDER_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_CRRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_CRRECORD_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_CRRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_CRRECORD_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKFOLDERREG_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKFOLDERREG_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKFOLDERREG_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKFOLDERREG_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKRECORDREG_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKRECORDREG_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKRECORDREG_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKRECORDREG_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKFOLDER_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKFOLDER_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKRECORD_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_TKRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_TKRECORD_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RDFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RDFOLDER_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RDFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RDFOLDER_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RDRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RDRECORD_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RDRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RDRECORD_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_ZZTRACE_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_ZZTRACE_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_ZZTRACE_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_ZZTRACE_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RCFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RCFOLDER_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RCFOLDER_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RCFOLDER_SQ01 INCREMENT BY 1 MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RCRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RCRECORD_SQ01 INCREMENT BY -' || L_VAL || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT TB_RCRECORD_SQ01.NEXTVAL FROM DUAL ' INTO L_VAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE TB_RCRECORD_SQ01 INCREMENT BY 1 MINVALUE 0';
END;
/

spool off
