set echo on
spool /data/oracle/admin/RMSORA9I/logs/15_InsertGrantGroup.log

/* *****************************************
 * 1. 기본권한그룹 등록
 * *****************************************
 */
INSERT INTO TB_STMENUGRANTGRP (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_GRANT_GRP_NM, MENU_GRANT_GRP_DESCR, USE_FLAG, WORK_USER_ID, WORK_DTIME, DEFAULT_GRANT_DIV)
VALUES ('0000001','001','일반사용자','일반사용자 메뉴권한그룹','1','0000000000','20140108090000','1');

INSERT INTO TB_STMENUGRANTGRP (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_GRANT_GRP_NM, MENU_GRANT_GRP_DESCR, USE_FLAG, WORK_USER_ID, WORK_DTIME, DEFAULT_GRANT_DIV)
VALUES ('0000001','002','처리과사용자','처리과사용자 메뉴권한그룹','1','0000000000','20140108090000','2');

INSERT INTO TB_STMENUGRANTGRP (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_GRANT_GRP_NM, MENU_GRANT_GRP_DESCR, USE_FLAG, WORK_USER_ID, WORK_DTIME, DEFAULT_GRANT_DIV)
VALUES ('0000001','003','기록관사용자','기록관사용자 메뉴권한그룹','1','0000000000','20140108090000','3');

INSERT INTO TB_STMENUGRANTGRP (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_GRANT_GRP_NM, MENU_GRANT_GRP_DESCR, USE_FLAG, WORK_USER_ID, WORK_DTIME, DEFAULT_GRANT_DIV)
VALUES ('0000001','004','시스템관리자','시스템관리자 메뉴권한그룹','1','0000000000','20140108090000','4');


/* *****************************************
 * 2. 권한그룹별 메뉴권한링크 등록
 * *****************************************
 */
-- 2-1.일반사용자 
INSERT INTO TB_STMENUGRANTLINK (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_ID, WORK_DTIME)
(
    SELECT TA.RECORD_CENTER_ID, TA.MENU_GRANT_GRP_CD, TA.MENU_ID, TA.WORK_DTIME
    FROM (
        SELECT A.RECORD_CENTER_ID, '001' AS MENU_GRANT_GRP_CD, A.MENU_ID, '20140108090000' AS WORK_DTIME
        FROM TB_STMENU A
        WHERE A.MENU_DIV_CD='4'
        AND A.USE_FLAG='1'
        AND A.MENU_GRANT_LEVL IN ('1')
        ORDER BY A.RECORD_CENTER_ID, A.MENU_ID
    ) TA
    WHERE NOT EXISTS (SELECT 1 FROM TB_STMENUGRANTLINK Z WHERE Z.RECORD_CENTER_ID=TA.RECORD_CENTER_ID AND Z.MENU_GRANT_GRP_CD=TA.MENU_GRANT_GRP_CD AND Z.MENU_ID=TA.MENU_ID)
);

-- 2-2.업무담당자 
INSERT INTO TB_STMENUGRANTLINK (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_ID, WORK_DTIME)
(
    SELECT TA.RECORD_CENTER_ID, TA.MENU_GRANT_GRP_CD, TA.MENU_ID, TA.WORK_DTIME
    FROM (
        SELECT A.RECORD_CENTER_ID, '002' AS MENU_GRANT_GRP_CD, A.MENU_ID, '20140108090000' AS WORK_DTIME
        FROM TB_STMENU A
        WHERE A.MENU_DIV_CD='4'
        AND A.USE_FLAG='1'
        AND A.MENU_GRANT_LEVL IN ('1','2')
        ORDER BY A.RECORD_CENTER_ID, A.MENU_ID
    ) TA
    WHERE NOT EXISTS (SELECT 1 FROM TB_STMENUGRANTLINK Z WHERE Z.RECORD_CENTER_ID=TA.RECORD_CENTER_ID AND Z.MENU_GRANT_GRP_CD=TA.MENU_GRANT_GRP_CD AND Z.MENU_ID=TA.MENU_ID)
);

-- 2-3.기록관담당자 (420~423 기록관현황 메뉴는 제외한다.)
INSERT INTO TB_STMENUGRANTLINK (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_ID, WORK_DTIME)
(
    SELECT TA.RECORD_CENTER_ID, TA.MENU_GRANT_GRP_CD, TA.MENU_ID, TA.WORK_DTIME
    FROM (
        SELECT A.RECORD_CENTER_ID, '003' AS MENU_GRANT_GRP_CD, A.MENU_ID, '20140108090000' AS WORK_DTIME
        FROM TB_STMENU A
        WHERE A.MENU_DIV_CD='4'
        AND A.USE_FLAG='1'
        AND A.MENU_GRANT_LEVL IN ('1','2','3','4')
        AND A.MENU_ID NOT IN ('418','419','420','421')
        ORDER BY A.RECORD_CENTER_ID, A.MENU_ID
    ) TA
    WHERE NOT EXISTS (SELECT 1 FROM TB_STMENUGRANTLINK Z WHERE Z.RECORD_CENTER_ID=TA.RECORD_CENTER_ID AND Z.MENU_GRANT_GRP_CD=TA.MENU_GRANT_GRP_CD AND Z.MENU_ID=TA.MENU_ID)
);

-- 2-4.시스템관리자 
INSERT INTO TB_STMENUGRANTLINK (RECORD_CENTER_ID, MENU_GRANT_GRP_CD, MENU_ID, WORK_DTIME)
(
    SELECT TA.RECORD_CENTER_ID, TA.MENU_GRANT_GRP_CD, TA.MENU_ID, TA.WORK_DTIME
    FROM (
        SELECT A.RECORD_CENTER_ID, '004' AS MENU_GRANT_GRP_CD, A.MENU_ID, '20140108090000' AS WORK_DTIME
        FROM TB_STMENU A
        WHERE A.MENU_DIV_CD='4'
        AND A.USE_FLAG='1'
        AND A.MENU_GRANT_LEVL IN ('4')
        ORDER BY A.RECORD_CENTER_ID, A.MENU_ID
    ) TA
    WHERE NOT EXISTS (SELECT 1 FROM TB_STMENUGRANTLINK Z WHERE Z.RECORD_CENTER_ID=TA.RECORD_CENTER_ID AND Z.MENU_GRANT_GRP_CD=TA.MENU_GRANT_GRP_CD AND Z.MENU_ID=TA.MENU_ID)
);




/* *****************************************
 * 3. 기록관설치용 시스템관리자 등록
 * *****************************************
 */
INSERT INTO TB_STUSER 
(RECORD_CENTER_ID, USER_ID, DEPT_CD, USER_DIV, USER_NM, LOGIN_USER_ID, USER_PWD, POS, RANK, WORK_FLAG
, TEL_NO, ADDR, RESID_NO, USE_FLAG, REG_DTIME, SSO_FLAG, LOGIN_ERROR_CNT, ONNARA_USERID, MENU_GRANT_GRP_CD, PKI_NAME_CHECK, ENCRYPT_FLAG) 
VALUES 
('0000001','0000000000', '', '4', '시스템설치자', 'rmsadmin', 'ooIqlA7zNNFcl09CmyifKBExG1Nx6rZA26rEyeXN3x0=', '설치담당', '담당', '1'
,'', '', '', '1', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),'1',0,'','004','N','1');



/* *****************************************
 * 4. 공동형관리자 세팅
 * *****************************************
 */
INSERT INTO TB_STUSER 
(RECORD_CENTER_ID, USER_ID, DEPT_CD, USER_DIV, USER_NM, LOGIN_USER_ID, USER_PWD, POS, RANK, WORK_FLAG
, TEL_NO, ADDR, RESID_NO, USE_FLAG, REG_DTIME, SSO_FLAG, LOGIN_ERROR_CNT, ONNARA_USERID, MENU_GRANT_GRP_CD, PKI_NAME_CHECK, ENCRYPT_FLAG) 
VALUES 
('0000001',(SELECT LPAD(NVL(MAX(user_id),0)+1,10,'0') FROM TB_STUSER), '', '5', '공동형관리자', 'multiadmin', '1YsLZUTBITw9h6Rwzae29xYo0DXhiHapxTjfFqSSNhI=', '공동형관리자', '담당', '1'
,'', '', '', '1', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),'1',0,'','','Y','1');


commit;

spool off;